"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export function CommunityFormEn() {
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/community", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: data.get("kind"), authorName: data.get("authorName"), email: data.get("email"), title: data.get("title"), content: data.get("content"), location: data.get("location"), anonymous: data.get("anonymous") === "on", consent: data.get("consent") === "on", website: data.get("website"), language: "en" }) }); if (!response.ok) throw new Error(); form.reset(); setStatus("success"); } catch { setStatus("error"); } }
  return <form className="community-form" onSubmit={submit}><label><span>What would you like to share?</span><select name="kind" defaultValue="story" required><option value="story">A story</option><option value="idea">An idea for couples</option><option value="surprise">A surprise that went well</option></select></label><div className="form-row"><label><span>Name or alias (optional)</span><input name="authorName" maxLength={80} /></label><label><span>Email address</span><input name="email" type="email" maxLength={160} required /></label></div><label><span>Title</span><input name="title" minLength={4} maxLength={120} required /></label><label><span>Your story or idea</span><textarea name="content" minLength={40} maxLength={3000} rows={9} required /><small>Avoid details that identify other people.</small></label><label><span>Place or city (optional)</span><input name="location" maxLength={120} /></label><label className="community-check"><input name="anonymous" type="checkbox" /><span>If it is published, I would like it to appear anonymously.</span></label><label className="community-check"><input name="consent" type="checkbox" required /><span>I authorize the editorial review of this submission and I have read the <Link href="/en/terms">Terms</Link>, the <Link href="/en/privacy">Privacy Policy</Link> and the <Link href="/en/community-guidelines">Community Guidelines</Link>.</span></label><label className="community-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><button className="button primary" disabled={status === "sending"}>{status === "sending" ? "Sending…" : "Send for review"} <span>→</span></button><p className={`community-message ${status}`} role="status" aria-live="polite">{status === "success" ? "Submission received. We will review it before anything is published." : status === "error" ? "We couldn't send it right now. Please check the fields and try again." : ""}</p></form>;
}
