import type { Metadata } from "next";
import { LegalPageEs } from "../legal/LegalPageEs";

export const metadata: Metadata = { title: "Política de privacidad", description: "Cómo trata Simple & Romantic los datos personales, las aportaciones y los mensajes.", alternates: { canonical: "/es/privacidad", languages: { "pt-BR": "/privacidade", "es-ES": "/es/privacidad" } } };

export default function PrivacyPageEs() {
  return <LegalPageEs kicker="TRANSPARENCIA Y CUIDADO" title="Política de privacidad" intro="Esta política explica, con un lenguaje sencillo, qué datos utilizamos y por qué. Última actualización: 23 de agosto de 2026.">
    <h2>1. Responsable del tratamiento</h2><p><strong>Responsable del tratamiento:</strong> Simple & Romantic, proyecto editorial independiente administrado por Bruno de Oliveira Cardoso.</p><p><strong>Contacto:</strong> las solicitudes relacionadas con la privacidad pueden enviarse mediante el <a href="/es/contacto">formulario de contacto del sitio</a>.</p>
    <h2>2. Datos que eliges enviar</h2><p>Podemos recibir nombre o alias, correo electrónico, ciudad, historias, ideas, mensajes de contacto e inscripciones. El correo de quien envía una aportación se usa para contacto y moderación y no se muestra públicamente.</p>
    <h2>3. Cómo y por qué usamos esos datos</h2><ul><li>con tu consentimiento, recibir y responder relatos de Entre nosotros y evaluar aportaciones para su publicación;</li><li>prestar el servicio solicitado, como responder un mensaje de contacto;</li><li>proteger el sitio y a sus lectores frente al spam, el fraude y los abusos;</li><li>cumplir obligaciones legales cuando corresponda.</li></ul><p>Puedes retirar tu consentimiento en cualquier momento, sin que ello invalide el tratamiento legítimo realizado anteriormente.</p>
    <h2>4. Publicación de historias</h2><p>Ninguna aportación se publica automáticamente. El equipo revisa el material y puede ajustar ortografía o claridad sin cambiar su sentido. Si eliges la publicación anónima, tu nombre no se mostrará.</p>
    <h2>5. Espacio Entre nosotros</h2><p>El espacio permite enviar un relato sin indicar nombre ni correo. Guardamos el alias opcional, la finalidad elegida, el relato, la autorización opcional para publicación, la respuesta preparada y un código aleatorio de seguimiento. El relato es privado por defecto. La autorización para una posible publicación es independiente y no garantiza que se publique.</p><p>No envíes nombres completos, direcciones, teléfonos, documentos, datos sanitarios identificables ni información que permita reconocer a terceras personas. Guarda el código con seguridad: permite consultar el estado y la respuesta vinculada.</p>
    <h2>6. Comunicación de datos</h2><p>No vendemos datos personales. Podemos utilizar proveedores técnicos necesarios para alojar el sitio y almacenar los datos, limitados a la prestación del servicio o al cumplimiento de la ley.</p>
    <h2>7. Estadísticas de uso</h2><p>Contamos visitas de páginas de forma agregada y sin cookies. El informe interno guarda únicamente el día, la página, el origen general de la visita y el número de visualizaciones. No almacenamos nombre, correo, dirección IP ni historial individual en esta medición.</p>
    <h2>8. Conservación y supresión</h2><ul><li><strong>Entre nosotros — nuevo o leído:</strong> hasta 180 días desde el envío;</li><li><strong>Entre nosotros — respondido:</strong> hasta 90 días desde la respuesta;</li><li><strong>Entre nosotros — archivado:</strong> hasta 30 días desde el cierre;</li><li><strong>Mensajes de contacto:</strong> hasta 12 meses desde la última interacción, salvo obligación legal;</li><li><strong>Aportaciones no publicadas:</strong> hasta 12 meses desde la decisión editorial;</li><li><strong>Aportaciones publicadas:</strong> mientras permanezcan en el blog o hasta retirar la autorización.</li></ul><p>Cada relato recibe una fecha de caducidad. Los registros caducados se eliminan durante las rutinas del servicio. También puedes borrarlo antes con el código particular en la página de consulta.</p>
    <h2>9. Tus derechos</h2><p>Puedes solicitar información, acceso, rectificación, supresión, limitación, portabilidad u oposición, así como retirar consentimientos, mediante la página de <a href="/es/contacto">Contacto</a>. En Entre nosotros, el código particular permite borrar directamente el relato. También puedes reclamar ante la autoridad de protección de datos de tu país de residencia o trabajo.</p>
    <h2>10. Menores y datos de terceros</h2><p>No envíes datos personales, imágenes ni historias identificables de terceros sin autorización. El servicio y Entre nosotros están destinados exclusivamente a personas mayores de 18 años.</p>
    <h2>11. Cambios</h2><p>Podemos actualizar esta política para reflejar nuevas funciones o requisitos legales. La fecha inicial identifica la versión vigente.</p>
  </LegalPageEs>;
}
