import type { BlogPost } from "../../../blog/posts";

export const posts: BlogPost[] = [
  {
    slug: "small-gestures-of-love",
    title: "25 Small Gestures of Love That Fit Into an Ordinary Day",
    seoTitle: "25 Small Gestures of Love",
    excerpt: "Discover 25 simple, tender gestures to show love in everyday life, strengthen your connection and turn ordinary days into small memories.",
    category: "SMALL GESTURES",
    series: "IDEIAS E GUIAS",
    image: "/images/blog/15-pequenos-gestos-amor.webp",
    imageAlt: "Adult couple sharing an affectionate moment on a balcony at the end of the afternoon",
    published: "August 24, 2026",
    publishedIso: "2026-08-24",
    readTime: "8 min read",
    intro: [
      "Not every special moment has to start with a reservation, a gift box or a date circled on the calendar.",
      "Sometimes it starts with a cup of coffee left ready.",
      "With a text in the middle of the afternoon.",
      "With five minutes of attention, phone nowhere in sight.",
      "Small gestures have a lovely advantage: they fit into real life. They fit into a tiring Tuesday, between two chores, on a tight budget, and even on those days when nobody woke up feeling particularly romantic.",
      "That's why we've gathered 25 simple ideas for showing affection without turning love into a Hollywood production.",
    ],
    sections: [
      { heading: "1. Take care of something your partner usually does alone", paragraphs: ["It could be making the coffee, filling the water bottle, tidying something up or getting a small task out of the way.", "No need to announce it.", "Sometimes affection works best when it simply appears."] },
      { heading: "2. Send a text for no reason at all", paragraphs: ["Don't wait for a birthday, an intense wave of missing them or some big news.", "A simple “just thought of you” can interrupt an ordinary day in a very good way."] },
      { heading: "3. Ask what the best part of their day was", paragraphs: ["It's a small question, but it opens a window.", "And when the answer comes, really listen."] },
      { heading: "4. Leave a hidden note", paragraphs: ["In a wallet, inside a book, in a bag, on the mirror, or anywhere they'll only find it later.", "It can be just one sentence.", "Part of the charm is in the discovery."] },
      { heading: "5. Play a song that's part of your story", paragraphs: ["No explanation.", "Let the first few seconds do the work."] },
      { heading: "6. Put your phone away for a few minutes", paragraphs: ["You don't have to declare an entire night without technology.", "Just try ten minutes of full presence.", "In a world that keeps flashing notifications, attention has become a rare gift."] },
      { heading: "7. Bring home something they love", paragraphs: ["A chocolate bar, a piece of fruit, a coffee, a favorite kind of bread.", "The value lies less in the object and more in the silent message:", "“I remember what you like.”"] },
      { heading: "8. Give a specific compliment", paragraphs: ["Instead of just saying “you look beautiful” or “you look handsome,” choose something you've really noticed.", "“I love the way you always try to make people feel at ease.”", "“You look so good when you're concentrating.”", "Being specific turns a compliment into recognition."] },
      { heading: "9. Send an old photo of the two of you", paragraphs: ["Pick a picture forgotten in your camera roll and add:", "“Remember this day?”", "An old photograph can open up a whole conversation."] },
      { heading: "10. Hug a few seconds longer", paragraphs: ["No rushing to let go.", "No need to say anything.", "Just stay."] },
      { heading: "11. Ask a question you wouldn't normally ask", paragraphs: ["“Is there anything you'd like to do with me this month?”", "“Where would you like to go with me?”", "“What have you been missing lately?”", "Relationships need curiosity, too."] },
      { heading: "12. Set up a space for them to rest", paragraphs: ["Straighten the couch, dim the lights, grab a blanket or put on some quiet music.", "Turning an ordinary room into a cozy one takes only a few minutes."] },
      { heading: "13. Say thank you for something everyday", paragraphs: ["Some things happen so often that they become invisible.", "“Thank you for always remembering that.”", "“Thank you for doing that yesterday.”", "Acknowledging the everyday keeps care from turning into a silent obligation."] },
      { heading: "14. Share something funny that is so you two", paragraphs: ["An image, a video, an inside joke.", "Couples also build intimacy by laughing at the same silly things.", "And that's wonderful."] },
      { heading: "15. Keep them company during a boring chore", paragraphs: ["Folding laundry, cooking, tidying the house, going grocery shopping.", "The chore may still be boring.", "But you can make it a little less lonely."] },
      { heading: "16. Ask: “Is there anything I can do to make your day a little lighter?”", paragraphs: ["There won't always be a big answer.", "Maybe it's just fetching something, taking care of a task or offering a few minutes of quiet.", "Even so, the question says I care."] },
      { heading: "17. Pick a little surprise for the end of the day", paragraphs: ["A dessert.", "A ten-minute walk.", "A cup of tea.", "A song.", "An episode of a show.", "A surprise doesn't have to be big to create anticipation."] },
      { heading: "18. Name a quality you admire", paragraphs: ["Not just looks.", "Courage, kindness, humor, patience, creativity, responsibility, generosity.", "Being loved also means feeling seen."] },
      { heading: "19. Recreate a little piece of a memory", paragraphs: ["Pick up something you ate on an early date.", "Walk down a street you used to love.", "Play a song.", "Recreate a photograph.", "You don't have to rebuild the whole day. A single detail can bring the memory back."] },
      { heading: "20. Plan an impromptu mini-date", paragraphs: ["Grab two drinks and sit out on the balcony.", "Take a walk around the neighborhood.", "Eat something in the car.", "Sit in a park.", "A date begins when you decide to treat that moment like one."] },
      { heading: "21. Ask whether they want to talk or just want company", paragraphs: ["There are days when we want to tell everything.", "On others, we just want someone nearby.", "Knowing the difference is a gentle form of care."] },
      { heading: "22. Do something that makes tomorrow morning easier", paragraphs: ["Leave something prepared.", "Set up the coffee.", "Set aside what will be needed.", "The gesture happens today, but the affection won't be discovered until tomorrow."] },
      { heading: "23. Say something tender before bed", paragraphs: ["It doesn't have to be an elaborate declaration.", "“I loved being with you today.”", "“Sleep well.”", "“It was nice having you here.”", "A few simple words close the day with a different texture."] },
      { heading: "24. Create a little tradition of your own", paragraphs: ["A song on Sundays.", "A walk after dinner.", "A special coffee on Fridays.", "A question before bed.", "Traditions don't have to be old. Somebody just has to invent them first."] },
      { heading: "25. Ask: “What could we do together today?”", paragraphs: ["Maybe the answer will be completely simple.", "And that's exactly the point."] },
      {
        heading: "Love Also Lives in the In-Betweens",
        paragraphs: [
          "Big moments are wonderful.",
          "Trips, birthdays, surprises and special dates deserve their space.",
          "But a relationship doesn't happen only on those days.",
          "It happens mostly between them.",
          "In the kitchen.",
          "On the way home.",
          "In a quick text.",
          "In the way someone notices the other is tired.",
          "In a hug before heading out.",
          "In the small signals that say, again and again:",
          "“I still see you.”",
          "You don't have to do all 25 gestures on this list.",
          "Pick one.",
          "Do it today.",
        ],
        paragraphLink: { before: "And if you'd like to turn another ordinary day into a little date, check out our guide ", linkText: "30 Simple Dates on a Small Budget", href: "/en/guide", after: "." },
        afterParagraphs: ["Because romance doesn't have to wait for a special occasion.", "Sometimes, the occasion is simply today."],
      },
    ],
  },
  {
    slug: "story-the-look-that-stayed",
    title: "The Look That Stayed",
    excerpt: "A story about two people who almost lost each other in the rush, and found again, in a simple look, the courage to choose each other once more.",
    category: "STORIES",
    series: "CONTOS",
    contentNotice: {
      label: "FICTIONAL STORY",
      text: "This story is a work of fiction. The characters and events were created for this post.",
    },
    image: "/images/blog/13-o-olhar-que-ficou.webp",
    imageAlt: "Adult couple holding hands and sharing a tender look at an outdoor café by the sea",
    published: "August 2, 2026",
    publishedIso: "2026-08-02",
    readTime: "7 min read",
    intro: [
      "Helena realized Rafael didn't look at her the way he used to. It wasn't a lack of love, she thought. It was hurry. The two of them had learned to talk while hunting for keys, answering texts and checking the time. Even their kisses seemed to know the bus wouldn't wait.",
      "That Sunday, they sat down at a small café terrace facing the sea. There was no anniversary, no apology, no important decision to make. Just two cups, the end of the afternoon, and a silence that, for the first time in a long while, neither of them rushed to fill.",
    ],
    sections: [
      {
        heading: "One Second Longer",
        paragraphs: [
          "Rafael looked up as Helena pushed back a strand of hair the wind had carried. She held his gaze. One second. Then another. It wasn't a challenge or a question. It was the almost-forgotten recognition of someone who knows the face in front of her and can still discover it all over again.",
          "He smiled sideways, the way he did in the beginning. Helena felt like laughing, but she didn't look away. The city carried on behind them — glasses on tables, footsteps on the sidewalk, a bicycle passing by — and for a few moments, everything seemed to be happening farther away.",
          "“How long has it been since we did this?” she asked. Rafael didn't pretend not to understand. He set his phone face down and answered, “Too long.”",
        ],
      },
      {
        heading: "The Hand on the Table",
        paragraphs: [
          "Helena told him she missed being noticed before she had to ask. She didn't want grand gestures. She wanted him to notice when she came home tired, to ask without looking at a screen, and to stay close enough to hear the whole answer.",
          "Rafael listened without getting defensive. Then he admitted that he missed her too, even though they slept in the same bed. He was afraid that every attempt to get closer would come at the wrong time, so he kept waiting for a perfect moment that never showed up.",
          "His hand moved slowly across the table. It didn't grab hers; it simply stayed there, offering space. Helena brought her fingers closer and wove them through his. The gesture was small, but it said it clearly: I'm still here.",
        ],
      },
      {
        heading: "The Way Back",
        paragraphs: [
          "By the time they left the café, the sky was a blend of pink and blue. They walked without hurrying. Rafael opened the car door, and Helena teased that the courtesy seemed like something from another era. “Then let's bring it back,” he said.",
          "Before getting in, she touched his face and kissed his forehead. Not as a reward, but as an answer. Rafael closed his eyes for a moment. Then he looked at her again — all of him, attentive, not searching for the next task.",
          "They didn't promise never to get distracted again. They promised something more honest: to notice when they were disappearing from each other's sight, and to make, even on an ordinary day, a few minutes to find their way back.",
        ],
      },
      {
        heading: "What to Take From This Story",
        paragraphs: [
          "Intimacy is also built in the way two people see each other. A lingering look, an offered hand, a kiss on the forehead or a question asked with real attention can bring presence back to a relationship worn down by routine.",
          "This week, try putting your phones away for ten minutes and looking at each other without hurrying. You don't have to turn the moment into a declaration or fix everything. Just start by saying: “I'm here. How are you, really?”",
        ],
      },
    ],
  },
  {
    slug: "weekly-tip-ten-minutes-of-presence",
    title: "Tip of the Week: Ten Minutes of Presence Are Worth More Than a Perfect Plan",
    seoTitle: "Ten Minutes of Presence for Couples",
    excerpt: "A short practice to break out of autopilot, listen with attention and care for your relationship in the middle of an ordinary week.",
    category: "TIP OF THE WEEK",
    series: "CONSELHO DA SEMANA",
    image: "/images/blog/07-reconectar.webp",
    imageAlt: "Adult couple talking attentively and holding hands by the river",
    published: "July 31, 2026",
    publishedIso: "2026-07-31",
    readTime: "4 min read",
    intro: [
      "Not every week leaves room for a long date. Still, there's almost always a small window when two people can step out of autopilot and notice each other again.",
      "This Tuesday's tip is simple: set aside ten minutes of full presence. Not to organize chores or solve every problem, but to find out how the person next to you really is.",
    ],
    sections: [
      {
        heading: "How to Do the Ten-Minute Check-In",
        items: [
          "Pick a moment that works and keep your phones out of reach.",
          "For five minutes, one person talks and the other just listens, without interrupting or preparing a reply.",
          "Then switch roles for the remaining five minutes.",
          "Finish by naming one small thing that could make the week lighter for both of you.",
        ],
      },
      {
        heading: "A Question to Start With",
        paragraphs: [
          "If you don't know where to begin, try: “What took up the most space inside you today?” The question doesn't demand a perfect answer, and it opens the door to talking about tiredness, joy, worry or anticipation.",
          "Listening doesn't mean agreeing with everything or immediately finding a solution. It means offering attention before offering advice.",
        ],
      },
      {
        heading: "The Small Commitment of the Week",
        paragraphs: [
          "Choose one realistic gesture based on your conversation: sharing a chore, taking a walk together, making coffee or simply repeating the ten minutes on another day.",
          "Relationships aren't sustained by big plans alone. Often, it's these small spaces of presence that remind both of you that you're still on the same team.",
        ],
      },
    ],
  },
  {
    slug: "story-the-table-by-the-window",
    title: "The Table by the Window",
    excerpt: "A story about two people, a dinner that almost didn't happen, and the gentleness of learning to pay attention again.",
    category: "STORIES",
    series: "CONTOS",
    contentNotice: {
      label: "FICTIONAL STORY",
      text: "This story is a work of fiction. The characters and events were created for this post.",
    },
    image: "/images/blog/16-a-mesa-perto-da-janela.webp",
    imageAlt: "Adult couple talking at home while rain falls outside",
    published: "July 31, 2026",
    publishedIso: "2026-07-31",
    readTime: "6 min read",
    intro: [
      "By the time Clara got home, the rain had already blurred the outlines of the buildings across the street. She found Miguel in the kitchen, frozen in front of two pots and a recipe open on his phone.",
      "“I was going to make that dinner,” he said, looking at a sauce that clearly hadn't cooperated. Clara set down her bag, tasted a drop with the tip of a spoon and tried not to laugh. She couldn't. Miguel laughed too, at first without much heart, then like someone finally letting go of the weight of the day.",
    ],
    sections: [
      {
        heading: "The Plan That Went Wrong",
        paragraphs: [
          "The reservation had been canceled because of the storm. Miguel wanted to save the night by recreating the restaurant's dish at home. He couldn't find two of the ingredients, burned the garlic and dropped half the salt onto the counter.",
          "Clara could have opened the food delivery app. Instead, she took eggs, a tomato and the last bit of cheese out of the fridge. “Let's have whatever the house allows,” she suggested.",
          "They made a lopsided omelet, split the last of the bread and carried everything to the little table by the window. Neither of them could remember the last time they'd sat there without a computer, bills or a to-do list between them.",
        ],
      },
      {
        heading: "The Forgotten Question",
        paragraphs: [
          "For a few minutes, they watched the water run down the glass. Miguel said he'd been sleeping badly. Clara confessed she missed talking without every sentence having to end in a decision.",
          "“When did we get so busy?” she asked. Miguel didn't know how to answer. He reached his hand across the table and let the silence do what answers couldn't.",
          "That night they didn't settle the work that was behind, the tight budget or the trip that still had no date. They agreed on just one thing: every Wednesday, they'd have dinner at that table, even if there was only bread, eggs and twenty minutes to spare.",
        ],
      },
      {
        heading: "After the Rain",
        paragraphs: [
          "The storm eased before dessert, which was an apple cut in half. Miguel put his phone away. Clara switched on the little lamp in the living room. The city came back into view behind the window, shining wet and imperfect.",
          "The dinner that almost didn't happen ended without a single photo. Even so, weeks later, when someone asked about a special night, both of them thought of the lopsided omelet, the rain and the table that had taught them to fit into each other's lives again.",
        ],
      },
    ],
  },
];
