import type { Metadata } from "next";
import { LegalPageEn } from "../legal/LegalPageEn";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Simple & Romantic handles personal data, submissions and messages.", alternates: { canonical: "/en/privacy", languages: { "pt-BR": "/privacidade", "es-ES": "/es/privacidad", "en": "/en/privacy", "x-default": "/privacidade" } } };

export default function PrivacyPageEn() {
  return <LegalPageEn kicker="TRANSPARENCY AND CARE" title="Privacy Policy" intro="This policy explains, in plain language, what data we use and why. Last updated: August 23, 2026.">
    <h2>1. Data controller</h2><p><strong>Data controller:</strong> Simple & Romantic, an independent editorial project run by Bruno de Oliveira Cardoso.</p><p><strong>Contact:</strong> privacy-related requests can be sent through the <a href="/en/contact">site's contact form</a>.</p>
    <h2>2. Data you choose to send</h2><p>We may receive a name or alias, email address, city, stories, ideas, contact messages and sign-ups. The email address of anyone who sends a submission is used for contact and moderation and is not shown publicly.</p>
    <h2>3. How and why we use this data</h2><ul><li>with your consent, to receive and respond to Between Us stories and to assess submissions for publication;</li><li>to provide the requested service, such as replying to a contact message;</li><li>to protect the site and its readers from spam, fraud and abuse;</li><li>to comply with legal obligations where applicable.</li></ul><p>You may withdraw your consent at any time, without affecting the lawfulness of the processing carried out before.</p>
    <h2>4. Publishing stories</h2><p>No submission is published automatically. The team reviews the material and may adjust spelling or clarity without changing its meaning. If you choose anonymous publication, your name will not be shown.</p>
    <h2>5. The Between Us space</h2><p>The space lets you send a story without giving a name or email. We store the optional alias, the chosen purpose, the story, the optional authorization for publication, the prepared reply and a random tracking code. The story is private by default. The authorization for possible publication is separate and does not guarantee that it will be published.</p><p>Do not send full names, addresses, phone numbers, documents, identifiable health data or information that would allow third parties to be recognized. Keep the code safe: it lets you check the status and the linked reply.</p>
    <h2>6. Sharing of data</h2><p>We do not sell personal data. We may use technical providers needed to host the site and store data, limited to providing the service or complying with the law.</p>
    <h2>7. Usage statistics</h2><p>We count page views in aggregate and without cookies. The internal report stores only the day, the page, the general origin of the visit and the number of views. We do not store name, email, IP address or individual history in this measurement.</p><p>If you enter your city in the idea generator, your browser queries open map services (Nominatim and Overpass, from OpenStreetMap) to learn which kinds of places are nearby, and stores the result only on your device (localStorage) for up to 30 days. We do not save the city on our server and you can clear it at any time. Those services receive the city text and your IP address, as with any internet request. If you use the location button, your browser asks for permission and the coordinates are used only for that map query: we do not store them.</p>
    <h2>8. Retention and deletion</h2><ul><li><strong>Between Us — new or read:</strong> up to 180 days from submission;</li><li><strong>Between Us — answered:</strong> up to 90 days from the reply;</li><li><strong>Between Us — archived:</strong> up to 30 days from closure;</li><li><strong>Contact messages:</strong> up to 12 months from the last interaction, unless required by law;</li><li><strong>Unpublished submissions:</strong> up to 12 months from the editorial decision;</li><li><strong>Published submissions:</strong> for as long as they remain on the blog or until the authorization is withdrawn.</li></ul><p>Each story is given an expiry date. Expired records are deleted during the service's routine maintenance. You can also delete it earlier using your personal code on the lookup page.</p>
    <h2>9. Your rights</h2><p>You may request information, access, rectification, erasure, restriction, portability or objection, as well as withdraw consents, through the <a href="/en/contact">Contact</a> page. In Between Us, your personal code lets you delete the story directly. You may also lodge a complaint with the data protection authority in your country of residence or work.</p>
    <h2>10. Minors and third-party data</h2><p>Do not send personal data, images or identifiable stories about third parties without their authorization. The service and Between Us are intended exclusively for people over 18.</p>
    <h2>11. Changes</h2><p>We may update this policy to reflect new features or legal requirements. The date at the top identifies the current version.</p>
  </LegalPageEn>;
}
