export type FinderLang = "pt" | "es" | "en";

type Opt = { value: string; label: string };
export type FinderCopy = {
  kicker: string; title: string; text: string;
  environment: string; budget: string; time: string; occasion: string;
  environments: Opt[]; budgets: Opt[]; times: Opt[]; occasions: Opt[]; periods: Opt[]; period: string;
  find: string; three: string; threeTitle: string; noMatchText: string; noMatchBtn: string; resultKicker: string; anotherIdea: string;
  finding: string; aiNote: string; exhausted: string; tip: string;
  surprise: string; planB: string; confirm: string;
  flameTitle: string; flameLabel: string; flameHint: string; flameAskTitle: string; flameAskText: string; flameYes: string; flameNo: string; flameBadge: string; flameRelaxed: string; flameNote: string;
  placeTitle: string; placeHint: string; placeHolder: string; placeBtn: string; placeBusy: string; placeOk: string; placeFail: string; placeClear: string; placeHere: string; placeDenied: string; placeHelp: Record<string, string>; placeUnavailable: string; placeTimeout: string; placeMap: string
  cost: Record<string, string>; duration: Record<string, string>; place: Record<string, string>; periodLabel: Record<string, string>;
};

export const finderCopy: Record<FinderLang, FinderCopy> = {
  pt: {
    kicker: "O PLANO COMEÇA AQUI", title: "O que vocês gostariam de viver hoje?", text: "Conte o essencial. A gente transforma isso em um encontro possível.",
    environment: "Que tipo de programa vocês querem?", budget: "Quanto vocês querem gastar?", time: "Quanto tempo vocês têm?", occasion: "Qual é a ocasião?",
    environments: [{ value: "home", label: "Em casa" }, { value: "outdoors", label: "Ao ar livre" }, { value: "go-out", label: "Sair" }, { value: "any", label: "Tanto faz" }],
    budgets: [{ value: "free", label: "Grátis" }, { value: "low", label: "Baixo custo" }, { value: "more", label: "Um pouco mais" }],
    times: [{ value: "hour", label: "1 hora" }, { value: "afternoon", label: "Uma tarde" }, { value: "day", label: "Um dia" }],
    occasions: [{ value: "casual", label: "Encontro casual" }, { value: "surprise", label: "Uma surpresa" }, { value: "reconnect", label: "Reconectar" }],
    period: "Que momento do dia?", periods: [{ value: "any", label: "Tanto faz" }, { value: "day", label: "De dia" }, { value: "night", label: "À noite" }],
    find: "Criar o nosso encontro", three: "Me dê 3 ideias", threeTitle: "3 ideias para vocês", noMatchText: "Nenhuma ideia combinou com vocês? Tudo bem. Torcemos para que uma delas inspire um dia ou uma noite incrível a dois. 💛", noMatchBtn: "Me dê outras 3 ideias", resultKicker: "UMA IDEIA PARA VOCÊS", anotherIdea: "Quero outra ideia",
    finding: "Procurando uma ideia para vocês…", aiNote: "Ideia criada na hora para os seus filtros. Confira detalhes e horários antes de sair.",
    exhausted: "Ainda não temos uma ideia para estes filtros. Tente mudar o tempo, o orçamento ou o tipo de programa.", tip: "Pequeno detalhe",
    surprise: "Surpresa:", planB: "Plano B:", confirm: "Confirme antes:",
    cost: { C0: "Grátis", C1: "Baixo custo", C2: "Um pouco mais" }, duration: { hour: "1 hora", afternoon: "Uma tarde", day: "Um dia" }, place: { home: "Em casa", outdoors: "Ao ar livre", "go-out": "Sair", any: "Tanto faz" }, periodLabel: { day: "De dia", night: "À noite" },
    flameTitle: "Modo Chama (+18)", flameLabel: "Ativar o modo Chama 🔥", flameHint: "Ideias mais íntimas e sensuais, para maiores de 18 anos. Sem nada explícito e sempre com consentimento.",
    flameAskTitle: "Conteúdo para adultos (+18)", flameAskText: "O modo Chama sugere encontros mais íntimos e sensuais, sem imagens e sem nada explícito. É destinado a maiores de 18 anos.", flameYes: "Tenho 18 anos ou mais", flameNo: "Agora não",
    flameBadge: "Modo Chama", flameRelaxed: "Não havia uma ideia exata para esses filtros. Aqui vai uma que combina com o clima.", flameNote: "Combinem antes o que é bem-vindo. Qualquer um pode dizer “passo” ou parar, a qualquer momento.",
    placeTitle: "Sua cidade (opcional)", placeHint: "Assim só sugerimos programas que existem aí perto (praia, cinema, parque…). Usamos dados abertos de mapas, direto no seu navegador, e não guardamos nada no nosso servidor.", placeHolder: "Ex.: Lisboa, Madri, Curitiba", placeBtn: "Usar esta cidade", placeBusy: "Procurando lugares perto de…", placeOk: "Ideias ajustadas para", placeFail: "Não consegui consultar esse lugar agora (ou a localização não foi permitida). Vamos mostrar ideias para qualquer lugar.", placeClear: "Limpar cidade", placeHere: "📍 Usar minha localização", placeHelp: { title: "Libere a localização em 3 passos", chrome: "1. Clique no ícone do pino riscado (ou do cadeado) na barra de endereço, ao lado do nome do site.|2. Em “Localização”, escolha “Permitir”.|3. Clique em “Tentar de novo” aqui embaixo.", safari: "1. No menu do Safari, abra Ajustes e depois Sites.|2. Escolha “Localização” e, em simpleandromantic.com, selecione “Permitir”.|3. Clique em “Tentar de novo” aqui embaixo.", firefox: "1. Clique no ícone de permissões, à esquerda do endereço do site.|2. Ao lado de “Acessar a sua localização”, clique no X para remover o bloqueio.|3. Clique em “Tentar de novo” aqui embaixo.", ios: "1. No Safari, toque em “aA” (ou no ícone de página) na barra de endereço e abra “Ajustes do Site”.|2. Em “Localização”, escolha “Permitir”. Se não houver essa opção, abra Ajustes do iPhone > Privacidade e Segurança > Serviços de Localização e ligue o seu navegador.|3. Volte aqui e toque em “Tentar de novo”.", android: "1. Toque no cadeado ao lado do endereço do site.|2. Toque em Permissões, depois em Localização, e escolha “Permitir”.|3. Clique em “Tentar de novo” aqui embaixo.", other: "1. Procure o ícone de cadeado ou de localização ao lado do endereço do site.|2. Mude a permissão de Localização para “Permitir”.|3. Clique em “Tentar de novo” aqui embaixo.", retry: "Tentar de novo", typeCity: "Prefiro digitar a cidade", close: "Fechar" }, placeDenied: "O navegador não permitiu a localização. Clique no cadeado ao lado do endereço do site, libere a localização e tente de novo, ou digite a cidade.", placeUnavailable: "O aparelho não conseguiu descobrir a sua localização (no Mac, confira em Ajustes do Sistema → Privacidade e Segurança → Serviços de Localização). Você pode digitar a cidade.", placeTimeout: "A localização demorou demais. Tente de novo ou digite a cidade.", placeMap: "Achei a sua localização, mas o serviço de mapas não respondeu agora. Tente de novo em instantes ou digite a cidade.",
  },
  es: {
    kicker: "EL PLAN EMPIEZA AQUÍ", title: "¿Qué os gustaría vivir hoy?", text: "Contadnos lo esencial. Lo convertimos en una cita posible.",
    environment: "¿Qué tipo de plan queréis?", budget: "¿Cuánto queréis gastar?", time: "¿Cuánto tiempo tenéis?", occasion: "¿Cuál es la ocasión?",
    environments: [{ value: "home", label: "En casa" }, { value: "outdoors", label: "Al aire libre" }, { value: "go-out", label: "Salir" }, { value: "any", label: "Me da igual" }],
    budgets: [{ value: "free", label: "Gratis" }, { value: "low", label: "Bajo coste" }, { value: "more", label: "Un poco más" }],
    times: [{ value: "hour", label: "1 hora" }, { value: "afternoon", label: "Una tarde" }, { value: "day", label: "Un día" }],
    occasions: [{ value: "casual", label: "Cita informal" }, { value: "surprise", label: "Una sorpresa" }, { value: "reconnect", label: "Reconectar" }],
    period: "¿En qué momento del día?", periods: [{ value: "any", label: "Me da igual" }, { value: "day", label: "De día" }, { value: "night", label: "De noche" }],
    find: "Crear nuestra cita", three: "Dame 3 ideas", threeTitle: "3 ideas para vosotros", noMatchText: "¿Ninguna idea os ha convencido? No pasa nada. Ojalá una de ellas os inspire un día o una noche increíble en pareja. 💛", noMatchBtn: "Dame otras 3 ideas", resultKicker: "UNA IDEA PARA VOSOTROS", anotherIdea: "Quiero otra idea",
    finding: "Buscando una idea para vosotros…", aiNote: "Idea creada al momento para vuestros filtros. Comprobad detalles y horarios antes de salir.",
    exhausted: "Todavía no tenemos una idea para estos filtros. Probad a cambiar el tiempo, el presupuesto o el tipo de plan.", tip: "Un pequeño detalle",
    surprise: "Sorpresa:", planB: "Plan B:", confirm: "Confirmad antes:",
    cost: { C0: "Gratis", C1: "Bajo coste", C2: "Un poco más" }, duration: { hour: "1 hora", afternoon: "Una tarde", day: "Un día" }, place: { home: "En casa", outdoors: "Al aire libre", "go-out": "Salir", any: "Me da igual" }, periodLabel: { day: "De día", night: "De noche" },
    flameTitle: "Modo Llama (+18)", flameLabel: "Activar el modo Llama 🔥", flameHint: "Ideas más íntimas y sensuales, para mayores de 18 años. Nada explícito y siempre con consentimiento.",
    flameAskTitle: "Contenido para adultos (+18)", flameAskText: "El modo Llama propone citas más íntimas y sensuales, sin imágenes y sin nada explícito. Está dirigido a mayores de 18 años.", flameYes: "Tengo 18 años o más", flameNo: "Ahora no",
    flameBadge: "Modo Llama", flameRelaxed: "No había una idea exacta para esos filtros. Aquí tenéis una que encaja con el ambiente.", flameNote: "Acordad antes qué es bienvenido. Cualquiera puede decir “paso” o parar, en cualquier momento.",
    placeTitle: "Tu ciudad (opcional)", placeHint: "Así solo sugerimos planes que existen cerca de vosotros (playa, cine, parque…). Usamos datos abiertos de mapas, directamente en vuestro navegador, y no guardamos nada en nuestro servidor.", placeHolder: "Ej.: Madrid, Sevilla, Lisboa", placeBtn: "Usar esta ciudad", placeBusy: "Buscando lugares cerca de…", placeOk: "Ideas ajustadas para", placeFail: "No he podido consultar esa ciudad ahora. Mostraremos ideas para cualquier lugar.", placeClear: "Borrar ciudad", placeHere: "📍 Usar mi ubicación", placeHelp: { title: "Permite la ubicación en 3 pasos", chrome: "1. Haz clic en el icono del pin tachado (o del candado) en la barra de direcciones, junto al nombre del sitio.|2. En “Ubicación”, elige “Permitir”.|3. Pulsa “Intentar de nuevo” aquí abajo.", safari: "1. En el menú de Safari, abre Ajustes y luego Sitios web.|2. Elige “Ubicación” y, en simpleandromantic.com, selecciona “Permitir”.|3. Pulsa “Intentar de nuevo” aquí abajo.", firefox: "1. Haz clic en el icono de permisos, a la izquierda de la dirección del sitio.|2. Junto a “Acceder a tu ubicación”, haz clic en la X para quitar el bloqueo.|3. Pulsa “Intentar de nuevo” aquí abajo.", ios: "1. En Safari, toca “aA” (o el icono de página) en la barra de direcciones y abre “Ajustes del sitio web”.|2. En “Ubicación”, elige “Permitir”. Si no aparece, abre Ajustes del iPhone > Privacidad y seguridad > Localización y activa tu navegador.|3. Vuelve aquí y toca “Intentar de nuevo”.", android: "1. Toca el candado junto a la dirección del sitio.|2. Toca Permisos, luego Ubicación, y elige “Permitir”.|3. Pulsa “Intentar de nuevo” aquí abajo.", other: "1. Busca el icono de candado o de ubicación junto a la dirección del sitio.|2. Cambia el permiso de Ubicación a “Permitir”.|3. Pulsa “Intentar de nuevo” aquí abajo.", retry: "Intentar de nuevo", typeCity: "Prefiero escribir la ciudad", close: "Cerrar" }, placeDenied: "El navegador no permitió la ubicación. Haz clic en el candado junto a la dirección del sitio, permite la ubicación e inténtalo de nuevo, o escribe la ciudad.", placeUnavailable: "El dispositivo no pudo averiguar tu ubicación. Puedes escribir la ciudad.", placeTimeout: "La ubicación tardó demasiado. Inténtalo de nuevo o escribe la ciudad.", placeMap: "He encontrado tu ubicación, pero el servicio de mapas no respondió ahora. Inténtalo de nuevo en unos instantes o escribe la ciudad.",
  },
  en: {
    kicker: "YOUR PLAN STARTS HERE", title: "What would you like to experience today?", text: "Tell us the essentials. We'll turn them into a date you can actually enjoy.",
    environment: "What kind of plan would you like?", budget: "How much would you like to spend?", time: "How much time do you have?", occasion: "What's the occasion?",
    environments: [{ value: "home", label: "At home" }, { value: "outdoors", label: "Outdoors" }, { value: "go-out", label: "Going out" }, { value: "any", label: "Anything" }],
    budgets: [{ value: "free", label: "Free" }, { value: "low", label: "Low cost" }, { value: "more", label: "A bit more" }],
    times: [{ value: "hour", label: "1 hour" }, { value: "afternoon", label: "An afternoon" }, { value: "day", label: "A day" }],
    occasions: [{ value: "casual", label: "Casual date" }, { value: "surprise", label: "A surprise" }, { value: "reconnect", label: "Reconnect" }],
    period: "What time of day?", periods: [{ value: "any", label: "Anything" }, { value: "day", label: "Daytime" }, { value: "night", label: "Evening / night" }],
    find: "Create our date", three: "Give me 3 ideas", threeTitle: "3 ideas for you", noMatchText: "None of these felt right? That's okay. We hope one of them sparks an incredible day or night with your partner. 💛", noMatchBtn: "Give me 3 more ideas", resultKicker: "AN IDEA FOR YOU", anotherIdea: "Show another idea",
    finding: "Finding an idea for you…", aiNote: "Idea created just now for your filters. Check details and opening times before you go.",
    exhausted: "We don't have an idea for these filters yet. Try changing the time, budget or type of plan.", tip: "A little detail",
    surprise: "Surprise:", planB: "Plan B:", confirm: "Check first:",
    cost: { C0: "Free", C1: "Low cost", C2: "A bit more" }, duration: { hour: "1 hour", afternoon: "An afternoon", day: "A day" }, place: { home: "At home", outdoors: "Outdoors", "go-out": "Going out", any: "Anything" }, periodLabel: { day: "Daytime", night: "Evening / night" },
    flameTitle: "Flame mode (18+)", flameLabel: "Turn on flame mode 🔥", flameHint: "More intimate and sensual ideas, for adults aged 18 and over. Nothing explicit, and always with consent.",
    flameAskTitle: "Adult content (18+)", flameAskText: "Flame mode suggests more intimate and sensual dates, with no images and nothing explicit. It is meant for readers aged 18 and over.", flameYes: "I am 18 or older", flameNo: "Not now",
    flameBadge: "Flame mode", flameRelaxed: "There was no exact idea for those filters. Here is one that fits the mood.", flameNote: "Agree beforehand on what is welcome. Either of you can say “pass” or stop at any time.",
    placeTitle: "Your city (optional)", placeHint: "So we only suggest plans that exist near you (beach, cinema, park…). We use open map data, straight from your browser, and store nothing on our server.", placeHolder: "E.g.: London, Lisbon, Madrid", placeBtn: "Use this city", placeBusy: "Looking for places near…", placeOk: "Ideas tuned for", placeFail: "I couldn't look up that city right now. We'll show ideas for anywhere.", placeClear: "Clear city", placeHere: "📍 Use my location", placeHelp: { title: "Allow location in 3 steps", chrome: "1. Click the crossed-out pin icon (or the padlock) in the address bar, next to the site name.|2. Under “Location”, choose “Allow”.|3. Click “Try again” below.", safari: "1. In the Safari menu, open Settings and then Websites.|2. Choose “Location” and, for simpleandromantic.com, select “Allow”.|3. Click “Try again” below.", firefox: "1. Click the permissions icon, to the left of the site address.|2. Next to “Access your location”, click the X to remove the block.|3. Click “Try again” below.", ios: "1. In Safari, tap “aA” (or the page icon) in the address bar and open “Website Settings”.|2. Under “Location”, choose “Allow”. If that is missing, open iPhone Settings > Privacy & Security > Location Services and turn your browser on.|3. Come back here and tap “Try again”.", android: "1. Tap the padlock next to the site address.|2. Tap Permissions, then Location, and choose “Allow”.|3. Click “Try again” below.", other: "1. Look for the padlock or location icon next to the site address.|2. Set the Location permission to “Allow”.|3. Click “Try again” below.", retry: "Try again", typeCity: "I'd rather type the city", close: "Close" }, placeDenied: "The browser did not allow location access. Click the padlock next to the site address, allow location and try again, or type the city.", placeUnavailable: "Your device could not work out your location. You can type the city.", placeTimeout: "Location took too long. Try again or type the city.", placeMap: "I found your location, but the map service did not answer right now. Try again in a moment or type the city.",
  },
};
