import type { Metadata } from "next";
import Link from "next/link";
import { LanguageSetter } from "../../components/LanguageSetter";
import { BlogFooterEn, BlogHeaderEn } from "../blog/BlogChromeEn";
import { ListeningFormEn } from "./ListeningFormEn";

export const metadata: Metadata = { title: "Between Us — a space to be heard", description: "A private space for listening and support, for adults who need to put into words what they feel.", alternates: { canonical: "/en/between-us", languages: { "pt-BR": "/entre-nos", "es-ES": "/es/entre-nos", "en": "/en/between-us", "x-default": "/entre-nos" } }, openGraph: { locale: "en_US" } };

export default function ListeningPageEn() {
  return <main className="listening-page"><LanguageSetter lang="en" /><BlogHeaderEn />
    <section className="listening-hero section"><div className="listening-hero-copy"><p className="eyebrow">BETWEEN US · A SPACE TO BE HEARD</p><h1>You can speak.<br /><em>Your story matters.</em></h1><p>Sometimes, putting into words what we carry inside is the beginning of a little relief. Write in your own way. We will read you with respect.</p><div className="listening-hero-actions"><a className="button primary" href="#desahogarme">I want to let it out <span>↓</span></a><Link className="quiet-link" href="/en/between-us/reply">Check for a reply</Link></div></div><div className="listening-promise" aria-label="Our commitment"><span aria-hidden="true">♡</span><p>Our promise</p><strong>Listen before replying.</strong><small>No judgment. No automatic publishing. No empty answers.</small></div></section>
    <section className="listening-principles section" aria-label="How it works"><article><span>01</span><h2>Private by default</h2><p>Your story goes into a reserved area and never appears publicly on its own.</p></article><article><span>02</span><h2>You choose</h2><p>You can simply let it out, or ask for a word of support and reflection.</p></article><article><span>03</span><h2>A human reply</h2><p>Every message is reviewed individually. Nothing is answered automatically.</p></article></section>
    <section className="listening-form-section section" id="desahogarme"><div className="listening-form-intro"><p className="eyebrow">THIS MOMENT IS YOURS</p><h2>What is on your heart?</h2><p>You don&apos;t have to write well or explain everything. Avoid full names, phone numbers, addresses, documents and details that could identify other people.</p><aside className="listening-safety"><strong>This is not an emergency service.</strong><p>Messages are not monitored in real time. If there is immediate danger, call your local emergency number.</p><div><span><b>European Union:</b> <a href="tel:112">112</a></span><span><b>US and Canada:</b> <a href="tel:911">911</a></span><span><b>United Kingdom:</b> <a href="tel:999">999</a></span></div><small>For emotional support or a crisis line in your own country, you can find free and confidential helplines at <a href="https://findahelpline.com" target="_blank" rel="noopener noreferrer">findahelpline.com</a>.</small></aside></div><ListeningFormEn /></section>
    <section className="listening-aftercare section"><p className="eyebrow">WHAT HAPPENS NEXT</p><h2>You don&apos;t have to sit waiting in front of the screen.</h2><p>After you send your story, you will receive a private code. Keep it to check whether your story has been read and whether we have left a word for you.</p><Link className="button primary" href="/en/between-us/reply">I already have a code <span>→</span></Link></section>
    <BlogFooterEn />
  </main>;
}
