import type { Metadata } from "next";
import Link from "next/link";
import { LanguageSetter } from "../../components/LanguageSetter";
import guide from "../../../content/guide-es-es.json";
import { BlogFooterEs, BlogHeaderEs } from "../blog/BlogChromeEs";

export const metadata: Metadata = { title: "30 citas sencillas gastando poco | Guía gratuita", description: "Guía gratuita con 30 citas sencillas, pequeños detalles y planes alternativos para parejas.", alternates: { canonical: "/es/guia", languages: { "pt-BR": "/guia", "es-ES": "/es/guia", en: "/en/guide" } } };

export default function GuidePageEs() {
  return <main className="online-guide"><LanguageSetter lang="es-ES" /><BlogHeaderEs /><header className="guide-hero section"><p className="eyebrow">GUÍA GRATUITA · SIN CONTENIDO BLOQUEADO</p><h1>30 citas sencillas<br />gastando poco</h1><p>Ideas posibles para crear presencia, conversación y recuerdos bonitos usando lugares públicos y lo que ya tenéis.</p><div className="guide-hero-actions"><a className="button primary" href="#citas">Ver las 30 ideas <span>↓</span></a><Link className="quiet-link" href="/es/blog">Leer el blog</Link></div></header><section className="guide-principles section"><article><span>01</span><h2>Elegid sin presión</h2><p>No es una lista de obligaciones. Empezad por la idea que encaje en vuestro tiempo y energía.</p></article><article><span>02</span><h2>Adaptadlo a la vida real</h2><p>Comprobad el tiempo, transporte, accesibilidad, normas del lugar y lo que ya tenéis en casa.</p></article><article><span>03</span><h2>Cuidaos mutuamente</h2><p>El consentimiento, la seguridad y la comodidad importan más que cualquier guion o sorpresa.</p></article></section><section className="guide-list section" id="citas"><div className="section-heading centered"><p className="eyebrow">ELEGID UNA IDEA</p><h2>La cita empieza con lo posible.</h2><p>Cada plan incluye lugar, duración, qué llevar, un detalle afectivo y una alternativa.</p></div><div className="guide-grid">{guide.map((item) => <article className="guide-card" key={item.number}><div className="guide-card-head"><span>{item.number}</span><div><p>{item.cost} · {item.duration}</p><h2>{item.title}</h2></div></div><dl><div><dt>Dónde</dt><dd>{item.setting}</dd></div><div><dt>Qué llevar</dt><dd>{item.bring}</dd></div><div><dt>El plan</dt><dd>{item.plan}</dd></div><div><dt>Pequeño detalle</dt><dd>{item.detail}</dd></div><div><dt>Plan B</dt><dd>{item.backup}</dd></div></dl></article>)}</div></section><section className="guide-final section"><p className="eyebrow">AHORA OS TOCA A VOSOTROS</p><h2>Cread la cita número 31.</h2><p>Combinad una actividad, una conversación y un gesto que hable de vosotros. El objetivo no es completar una lista, sino volver a elegir tiempo juntos.</p><Link className="button primary" href="/es/#encontrar">Crear nuestra cita <span>→</span></Link></section><BlogFooterEs /></main>;
}
