import type { Metadata } from "next";
import Link from "next/link";
import { LanguageSetter } from "../../components/LanguageSetter";
import guide from "../../../content/guide-en.json";
import { BlogFooterEn, BlogHeaderEn } from "../blog/BlogChromeEn";

export const metadata: Metadata = { title: "30 simple dates on a small budget | Free guide", description: "A free guide with 30 simple dates, small gestures and backup plans for couples.", alternates: { canonical: "/en/guide", languages: { "pt-BR": "/guia", "es-ES": "/es/guia", "en": "/en/guide", "x-default": "/guia" } } };

export default function GuidePageEn() {
  return <main className="online-guide"><LanguageSetter lang="en" /><BlogHeaderEn /><header className="guide-hero section"><p className="eyebrow">FREE GUIDE · NO LOCKED CONTENT</p><h1>30 simple dates<br />on a small budget</h1><p>Realistic ideas for creating presence, conversation and lovely memories using public places and what you already have.</p><div className="guide-hero-actions"><a className="button primary" href="#dates">See all 30 ideas <span>↓</span></a><Link className="quiet-link" href="/en/blog">Read the blog</Link></div></header><section className="guide-principles section"><article><span>01</span><h2>Choose without pressure</h2><p>This is not a list of obligations. Start with the idea that fits your time and energy.</p></article><article><span>02</span><h2>Adapt it to real life</h2><p>Check the weather, transport, accessibility, the venue's rules and what you already have at home.</p></article><article><span>03</span><h2>Take care of each other</h2><p>Consent, safety and comfort matter more than any script or surprise.</p></article></section><section className="guide-list section" id="dates"><div className="section-heading centered"><p className="eyebrow">PICK AN IDEA</p><h2>A date starts with what is possible.</h2><p>Every plan includes a place, a duration, what to bring, a loving detail and a backup option.</p></div><div className="guide-grid">{guide.map((item) => <article className="guide-card" key={item.number}><div className="guide-card-head"><span>{item.number}</span><div><p>{item.cost} · {item.duration}</p><h2>{item.title}</h2></div></div><dl><div><dt>Where</dt><dd>{item.setting}</dd></div><div><dt>What to bring</dt><dd>{item.bring}</dd></div><div><dt>The plan</dt><dd>{item.plan}</dd></div><div><dt>Small detail</dt><dd>{item.detail}</dd></div><div><dt>Plan B</dt><dd>{item.backup}</dd></div></dl></article>)}</div></section><section className="guide-final section"><p className="eyebrow">NOW IT'S YOUR TURN</p><h2>Create date number 31.</h2><p>Combine an activity, a conversation and a gesture that speaks of the two of you. The goal is not to complete a list, but to keep choosing time together.</p><Link className="button primary" href="/en/#encontrar">Create our date <span>→</span></Link></section><BlogFooterEn /></main>;
}
