// Bloques de texto del horóscopo de pareja (ES, España, "vosotros"). Tono: equilibrio entre romántico y gracioso.
export default {
  moon: [
    ["La Luna se ha levantado con prisa", "Con la Luna en Aries, el día pide iniciativa: quien tenga una idea, que la diga ya. Cuidado, eso sí, con que la prisa no atropelle el cariño."],
    ["Día de pereza buena y cariño de verdad", "Con la Luna en Tauro, todo lo que sabe bien gana fuerza: buena comida, sofá, caricias lentas. Hoy el confort vale más que el plan."],
    ["La Luna está de cháchara", "Con la Luna en Géminis, el día es de charla, mensajes y cambiar de tema cada cinco minutos. Aprovechadlo: la conversación suelta es el mejor condimento de la pareja."],
    ["Luna en casa, corazón abierto", "Con la Luna en Cáncer, el corazón se ablanda y la casa se vuelve más acogedora. Día de mimos, de buenos recuerdos y de cuidar a quien se ama."],
    ["La Luna pide aplausos (y un abrazo)", "Con la Luna en Leo, apetece brillar y que se fijen en uno. Hoy un piropo sincero vale oro, y quien lo da también sale ganando."],
    ["La Luna ordena la casa", "Con la Luna en Virgo, el día es de detalles, de poner orden y de demostrar amor con gestos pequeños. Pero nadie tiene que ser perfecto para que lo quieran."],
    ["Día de equilibrar la balanza entre los dos", "Con la Luna en Libra, suben el encanto y la armonía. Buen día para decidir juntos, para el romance y para evitar discusiones tontas."],
    ["Luna profunda, mirada larga", "Con la Luna en Escorpio, las emociones se intensifican y las miradas se alargan. Día de conversación de verdad, de las que dan un escalofrío bonito."],
    ["La Luna quiere aventura", "Con la Luna en Sagitario, entran ganas de salir de la rutina, reír alto y decir que sí a lo inesperado. Un paseo improvisado sienta de maravilla."],
    ["Luna seria, corazón firme", "Con la Luna en Capricornio, el día es de compromiso y de construir despacio. Decir 'aquí estoy' vale más que cualquier discurso."],
    ["Luna rarita, como a vosotros os gusta", "Con la Luna en Acuario, el amor se vuelve original: nada de guion, todo sorpresa y amistad. Haced algo que nadie más haría."],
    ["Luna soñadora, hoy toca divagar", "Con la Luna en Piscis, la imaginación anda suelta y el corazón más sensible. Día de música, de mirar por la ventana y de hablar bajito."],
  ],
  phases: [
    "La Luna está nueva: un día estupendo para empezar de cero, pedir un deseo y plantar un plan pequeño.",
    "La Luna es creciente: lo que empecéis ahora cogerá fuerza en los próximos días.",
    "La Luna está en cuarto creciente: es hora de dar ese paso que estaba en duda.",
    "La Luna crece, casi llena: sube la energía, y también las ganas de hacerlo todo juntos.",
    "La Luna está llena: lo que estaba guardado sale a la luz y las emociones se ven más claras.",
    "La Luna empieza a menguar: buen momento para agradecer lo que ha salido bien y soltar lo demás.",
    "La Luna está en cuarto menguante: día de soltar lo que pesa y simplificar.",
    "La Luna es menguante: pide descanso, calma y conversación más bajita.",
  ],
  phaseNames: ["Luna nueva", "Luna creciente", "Cuarto creciente", "Gibosa creciente", "Luna llena", "Gibosa menguante", "Cuarto menguante", "Luna menguante"],
  events: {
    new: "Hoy es día de Luna nueva en {sign}: hay un nuevo comienzo en el aire. Cada uno pide un deseo pequeño para el mes.",
    full: "Hoy es día de Luna llena en {sign}: las emociones salen a flote y todo se ve más claro (y un poco más dramático).",
    first: "Hoy es cuarto creciente en {sign}: un empujoncito para sacar el plan del papel.",
    last: "Hoy es cuarto menguante en {sign}: día de soltar lo que pesa.",
  },
  aspects: [
    ["{A} y {B} sois del mismo signo: os entendéis sin subtítulos, y también tenéis los mismos defectos. Hoy, reíd de los defectos por partida doble.", "Mismo signo, mismas manías (las buenas y las no tanto). Cuando uno se reconoce en el otro, perdonar es fácil."],
    ["{A} y {B} sois signos vecinos, pero de maneras muy distintas: uno empieza donde el otro termina. La gracia está en sentir curiosidad por lo que no se parece a ti.", "Vecinos en el zodiaco y casi extranjeros en el modo de ser: {A} y {B} tenéis mucho que enseñaros."],
    ["{A} y {B} tenéis una afinidad fácil, de las que solo piden un empujoncito. Hoy, dadlo.", "Entre {A} y {B} las cosas fluyen con ligereza. Basta con aceptar la invitación que el otro hace sin darse cuenta."],
    ["Entre {A} y {B} hay una tensión rica, que pincha y hace crecer. Hoy, tratad la diferencia como un condimento y no como un defecto.", "{A} y {B} pensáis distinto, y por eso la conversación nunca se acaba. Hoy, escuchad hasta el final antes de responder."],
    ["{A} y {B} fluís juntos casi sin esfuerzo. El único riesgo es el piloto automático: un detalle nuevo hoy marca la diferencia.", "Entre {A} y {B} hay una sintonía natural. Para no caer en la rutina, haced alguna cosita fuera del guion."],
    ["{A} y {B} parece que habláis idiomas distintos, y eso es lo que hace interesante la historia. Hoy, traducíos el uno al otro con paciencia y risas.", "Entre {A} y {B}, lo que uno ve obvio, el otro ni se lo había planteado. Preguntar '¿por qué?' con cariño lo arregla casi todo."],
    ["{A} y {B} sois opuestos que se complementan: uno tiene lo que le falta al otro. Hoy, pídele prestado lo que no tienes.", "Los opuestos se atraen, y {A} y {B} sois la prueba. El consejo de hoy es admirar en el otro justo lo que tú no eres."],
  ],
  rulers: {
    mercury: "Los dos tenéis a Mercurio como regente, el planeta de la conversación: habláis el mismo idioma y os entendéis con palabras.",
    venus: "Los dos tenéis a Venus como regente, el planeta del amor y del placer: os gustan las mismas cosas buenas de la vida.",
    mars: "Los dos tenéis a Marte como regente, el planeta de la energía: el deseo y las ganas van de la mano.",
    jupiter: "Los dos tenéis a Júpiter como regente, el planeta de la abundancia y el optimismo: cuando os reís, os reís fuerte.",
    saturn: "Los dos tenéis a Saturno como regente, el planeta de la constancia: os tomáis el compromiso en serio y sabéis esperar.",
  },
  gives: ["valentía para empezar", "calma y un cariño que dura", "conversación y curiosidad", "cuidado y memoria afectiva", "calor y generosidad", "atención a los detalles", "encanto y ganas de armonía", "intensidad y lealtad", "alegría y ganas de explorar", "firmeza y constancia", "originalidad y libertad", "sensibilidad e imaginación"],
  givesLine: ["En la mezcla de hoy, {A} aporta {gA} y {B} aporta {gB}.", "{A} trae {gA}; {B} trae {gB}. Juntos ya tenéis lo esencial."],
  mercury: {
    retro: [
      "Mercurio está retrógrado y, según la tradición, es época de mensajes mal entendidos. Truco: antes de enfadarte, preguntad '¿qué has querido decir?'.",
      "Con Mercurio retrógrado, dice la tradición, toca releer antes de enviar y confirmar lo acordado. Nada que un buen '¿quedamos así?' no arregle.",
      "Mercurio marcha atrás: según la tradición, vuelven a la conversación temas antiguos. Si sale uno, tratadlo con ligereza.",
      "Dicen que con Mercurio retrógrado desaparecen los objetos y se lían los horarios. Poneos de acuerdo en reíros del desorden en vez de buscar culpables.",
    ],
    station: {
      retro: "Hoy Mercurio empieza a retroceder: según la tradición, conviene releer lo acordado antes de seguir.",
      direct: "Hoy Mercurio vuelve a avanzar: la conversación tiende a aclararse y los malentendidos, a escasear.",
    },
  },
  venus: {
    lead: "Venus, el planeta del amor, está en {sign}: {t}.",
    items: ["el amor tiene prisa y le gusta conquistar, así que tomad la iniciativa", "el amor es sensorial: caricias, comida y buen olor", "el amor llega por la conversación y el humor", "el amor pide mimos, hogar y memoria", "el amor quiere brillo y declaraciones en voz alta", "el amor aparece en los pequeños cuidados", "el amor está elegante y armonioso", "el amor se vuelve intenso y sin medias palabras", "el amor quiere libertad y aventura a dos", "el amor es firme y construye despacio", "el amor es amistad ante todo, y original", "el amor es romántico, soñador y entregado"],
  },
  mars: {
    lead: "Marte, el planeta de la energía y el deseo, está en {sign}: {t}.",
    items: ["energía de sobra y ganas de actuar", "ritmo lento y firme, con placer en los sentidos", "mente agitada, y la conversación es el mejor ejercicio", "el deseo llega por el cuidado y la seguridad", "ganas de brillar y de ser admirado", "energía para organizar, y conviene dedicarla también al placer", "el deseo pide armonía y cortejo", "deseo intenso y magnético", "ánimo para pasear y hacer deporte juntos", "energía disciplinada, buena para proyectos a dos", "ganas de hacer cosas fuera de lo común", "energía suave, más sueño que acción"],
  },
  sun: {
    lead: "El Sol está en {sign}: estación de {t}.",
    items: ["comienzos y valentía", "placeres sencillos y constancia", "conversación y curiosidad", "hogar y afecto", "calor y fiesta", "orden y cuidado", "equilibrio y pareja", "profundidad y cambio", "aventura y optimismo", "metas y compromiso", "novedad y amistad", "sueño y sensibilidad"],
  },
  gestures: {
    fire: ["Proponed algo nuevo para hacer juntos hoy, por sencillo que sea.", "Haz un piropo en voz alta, sin ningún motivo.", "Invita a un paseo de 15 minutos antes de cenar.", "Elegid un sitio para ver la puesta de sol e id andando.", "Reta al otro a un juego rápido, con un premio tonto para quien gane.", "Haz algo que siempre dejas para después y dedícaselo al otro.", "Di en voz alta tres cosas que admiras del otro.", "Bailad en la cocina mientras se hace la cena.", "Cambiad de sitio en el sofá y ved el día desde el punto de vista del otro.", "Planea una mini escapada sorpresa para el fin de semana, aunque sea solo a una panadería distinta.", "Contaos el sueño más loco que hayáis tenido.", "Pide al otro un consejo sobre algo pequeño y hazle caso."],
    earth: ["Prepara algo con las manos: un café, un bocadillo, una mesa bien puesta.", "Haz hoy una tarea que al otro le fastidia hacer.", "Deja una nota corta donde el otro la encuentre.", "Ordenad juntos un rincón de la casa que os molesta y celebradlo con una infusión.", "Cocinad juntos una receta sencilla que ninguno de los dos haya hecho.", "Masajea las manos del otro durante 3 minutos.", "Escribe en un papel algo que agradeces del otro y déjalo en el bolsillo de su abrigo.", "Pasead descalzos por la hierba o la alfombra y hablad de nada.", "Haced la cama juntos, despacio, como si fuera un ritual.", "Comprad una planta o una flor y elegid un nombre para ella.", "Deja preparada la ropa del otro para mañana, con cariño.", "Haced una comida sin móvil, solo vosotros y el plato."],
    air: ["Manda un mensaje 'me he acordado de ti porque…' con algo muy concreto.", "Haceos una pregunta curiosa y escuchad la respuesta entera.", "Elegid una canción y bailad 3 minutos en el salón.", "Intercambiad listas de reproducción: cada uno elige 3 canciones para el otro.", "Escribe una nota de 3 líneas y escóndela en un libro del otro.", "Haced un cuestionario de 5 preguntas sobre el día en que os conocisteis.", "Contaos qué pensasteis cuando os visteis por primera vez.", "Inventad juntos un apodo nuevo y gracioso que solo uséis vosotros.", "Leed en voz alta un trozo de libro, poema o receta, y comentadlo.", "Haceos una foto juntos poniendo caras raras y usadla de fondo de pantalla por un día.", "Pide al otro tres palabras y escribe una frase con ellas.", "Contaos una historia tonta de la infancia."],
    water: ["Abraza durante 20 segundos, sin decir nada.", "Cuenta un buen recuerdo de los dos y pide al otro que cuente el suyo.", "Pregunta '¿cómo estás de verdad?' y escucha hasta el final.", "Preparad una infusión o un baño caliente para el otro, sin pedir nada a cambio.", "Mirad fotos antiguas de los dos y elegid la favorita.", "Escribe tres líneas sobre cómo te hace sentir el otro y entrégaselas.", "Quedaos 5 minutos en silencio, de la mano.", "Escuchad juntos una canción que marcó vuestra historia.", "Haced una lista de cinco sitios donde os gustaría despertar juntos.", "Elegid una película antigua y verla abrazados, sin comentar.", "Pide perdón por algo pequeño que quedó pendiente, con un abrazo.", "Contaos qué es lo que más os gusta del olor, la voz o la risa del otro."],
  },
  moonGestures: ["Empezad algo pequeño hoy, aunque sea solo una canción nueva en la cocina.", "Haced una cena con mimo o una merienda rica, muy despacio.", "Intercambiad 10 mensajes divertidos a lo largo del día, aunque estéis juntos.", "Acaricia al otro y pregunta: '¿qué necesitas hoy?'.", "Haceos un piropo currado, de los de público.", "Haz un favor discreto que el otro solo notará más tarde.", "Elegid juntos un plan y que cada uno ceda en una cosa.", "Miraos a los ojos durante 30 segundos, sin hablar, y luego contad qué habéis sentido.", "Cambiad de camino hoy: volved a casa por una calle que nunca hayáis usado.", "Acordad una meta pequeña para el mes y apuntadla en el calendario.", "Haced algo que nunca hayáis hecho juntos, por pequeño que sea.", "Quedaos en cucharita cinco minutos, en silencio."],
  closings: [
    "Solo diversión, pero el beso es de verdad.",
    "Si sale bien, la Luna se lleva el mérito. Si sale mal, la culpa es de Mercurio.",
    "Ningún signo decide por vosotros, pero ayuda a sacar conversación.",
    "El cielo sugiere; quien decide es el abrazo.",
    "Hoy el horóscopo es solo una excusa para acercaros.",
    "Si nada de esto tiene sentido, al menos os habréis reído juntos.",
    "El universo no manda sobre vosotros, pero aprecia la iniciativa.",
    "Pequeños gestos, grandes efectos, y ningún planeta tiene por qué enterarse.",
    "Jugad sin presión: quien acierta gana un beso, y quien falla también.",
    "Previsión del día: probabilidad alta de cariño.",
    "Las estrellas miran desde lejos; quien abraza eres tú.",
    "Tomaos en serio solo el cariño; lo demás es broma.",
  ],
  chips: { moonIn: "Luna en {sign}", mercuryRetro: "Mercurio retrógrado", mercuryDirect: "Mercurio directo" },
};
