// Blocos de texto do horóscopo do casal (PT-BR). Tom: equilíbrio entre romântico e engraçado. Aprovado pelo Bruno em 07/10/2026.
export default {
  moon: [
    ["A Lua acordou com pressa", "Com a Lua em Áries, o dia pede iniciativa: quem tiver uma ideia, que a diga logo. Cuidado só para a pressa não atropelar o carinho."],
    ["Dia de preguiça boa e carinho de verdade", "Com a Lua em Touro, tudo o que é gostoso ganha força: comida boa, sofá, toque devagar. Hoje, o conforto vale mais que o programa."],
    ["A Lua está de conversa fiada", "Com a Lua em Gêmeos, o dia é de papo, mensagens e mudança de assunto a cada cinco minutos. Aproveitem: conversa solta é o melhor tempero do casal."],
    ["Lua em casa, coração aberto", "Com a Lua em Câncer, o coração fica mais mole e a casa mais acolhedora. Dia de colo, de memória boa e de cuidar de quem se ama."],
    ["A Lua pede aplauso (e abraço)", "Com a Lua em Leão, a vontade é de brilhar e de ser notado. Hoje, um elogio sincero vale ouro, e quem faz também ganha."],
    ["A Lua arruma a casa", "Com a Lua em Virgem, o dia é de detalhes, de pôr ordem e de mostrar amor em atos pequenos. Mas ninguém precisa ser perfeito para ser querido."],
    ["Dia de equilibrar a balança a dois", "Com a Lua em Libra, o charme e a harmonia sobem. É bom dia para decidir juntos, para o romance e para evitar discussão boba."],
    ["Lua funda, olhar demorado", "Com a Lua em Escorpião, as emoções ficam intensas e o olhar mais longo. Dia de conversa de verdade, daquelas que dão um friozinho bom."],
    ["A Lua quer aventura", "Com a Lua em Sagitário, vem vontade de sair da rotina, rir alto e topar o inesperado. Um passeio improvisado cai muito bem."],
    ["Lua séria, coração firme", "Com a Lua em Capricórnio, o dia é de compromisso e de construir devagar. Dizer 'estou aqui' vale mais que qualquer discurso."],
    ["Lua esquisita, do jeito que vocês gostam", "Com a Lua em Aquário, o amor fica original: nada de roteiro, tudo de surpresa e amizade. Façam algo que ninguém mais faria."],
    ["Lua sonhadora, hoje vale devanear", "Com a Lua em Peixes, a imaginação anda solta e o coração fica mais sensível. Dia de música, de olhar pela janela e de falar baixinho."],
  ],
  phases: [
    "A Lua está nova: ótimo dia para recomeçar, pedir um desejo e plantar um plano pequeno.",
    "A Lua é crescente: o que vocês começarem agora ganha força nos próximos dias.",
    "A Lua está em quarto crescente: hora de dar o passo que estava na dúvida.",
    "A Lua está crescendo, quase cheia: a energia sobe, e a vontade de fazer junto também.",
    "A Lua está cheia: o que estava guardado aparece, e as emoções ficam mais claras.",
    "A Lua começa a minguar: bom momento para agradecer o que deu certo e deixar o resto ir.",
    "A Lua está em quarto minguante: dia de soltar o que pesa e simplificar.",
    "A Lua é minguante: pede descanso, calma e conversa mais baixinha.",
  ],
  phaseNames: ["Lua nova", "Lua crescente", "Quarto crescente", "Crescente gibosa", "Lua cheia", "Minguante gibosa", "Quarto minguante", "Lua minguante"],
  events: {
    new: "Hoje é dia de Lua nova em {sign}: recomeço no ar. Cada um faz um pedido pequeno para o mês.",
    full: "Hoje é dia de Lua cheia em {sign}: as emoções vêm à tona e tudo fica mais claro (e um pouco mais dramático).",
    first: "Hoje é quarto crescente em {sign}: um empurrão para tirar o plano do papel.",
    last: "Hoje é quarto minguante em {sign}: dia de soltar o que pesa.",
  },
  aspects: [
    ["{A} e {B} são do mesmo signo: entendem-se sem legenda, e também têm os mesmos defeitos. Hoje, riam dos defeitos em dobro.", "Mesmo signo, mesmos hábitos (os bons e os nem tanto). Quando um se reconhece no outro, fica fácil perdoar."],
    ["{A} e {B} são signos vizinhos, mas de jeitos bem diferentes: um começa onde o outro termina. A graça é ficar curioso com o que não se parece com você.", "Vizinhos no zodíaco e quase estrangeiros no jeito de ser: {A} e {B} têm muito a mostrar um ao outro."],
    ["{A} e {B} têm uma afinidade fácil, daquelas que pedem só um empurrãozinho. Hoje, deem o empurrão.", "Entre {A} e {B} as coisas fluem com leveza. Basta aceitar o convite que o outro faz sem perceber."],
    ["Entre {A} e {B} há uma tensão gostosa, que cutuca e faz crescer. Hoje, tratem a diferença como tempero, e não como defeito.", "{A} e {B} pensam diferente, e é por isso que a conversa nunca acaba. Hoje, ouçam até o fim antes de responder."],
    ["{A} e {B} fluem juntos quase sem esforço. O único risco é o piloto automático: um detalhe novo hoje faz toda a diferença.", "Entre {A} e {B} existe uma sintonia natural. Para não cair na rotina, façam uma coisinha fora do roteiro."],
    ["{A} e {B} parecem falar línguas diferentes, e é isso que torna a história interessante. Hoje, traduzam um para o outro, com paciência e riso.", "Entre {A} e {B}, o que um acha óbvio, o outro nunca pensou. Perguntar 'por quê?' com carinho resolve quase tudo."],
    ["{A} e {B} são opostos que se completam: um tem o que falta ao outro. Hoje, peça emprestado o que você não tem.", "Opostos se atraem, e {A} e {B} são a prova. A dica de hoje é admirar no outro justamente o que você não é."],
  ],
  rulers: {
    mercury: "Os dois têm Mercúrio como regente, o planeta da conversa: falam a mesma língua e se entendem pelas palavras.",
    venus: "Os dois têm Vênus como regente, o planeta do amor e do prazer: gostam das mesmas coisas boas da vida.",
    mars: "Os dois têm Marte como regente, o planeta da energia: o desejo e a vontade andam juntos.",
    jupiter: "Os dois têm Júpiter como regente, o planeta da fartura e do otimismo: quando riem, riem alto.",
    saturn: "Os dois têm Saturno como regente, o planeta da constância: levam o compromisso a sério e sabem esperar.",
  },
  gives: ["coragem para começar", "calma e carinho que dura", "conversa e curiosidade", "cuidado e memória afetiva", "calor e generosidade", "atenção aos detalhes", "charme e vontade de harmonia", "intensidade e lealdade", "alegria e vontade de explorar", "firmeza e constância", "originalidade e liberdade", "sensibilidade e imaginação"],
  givesLine: ["Na mistura de hoje, {A} entra com {gA} e {B} com {gB}.", "{A} traz {gA}; {B} traz {gB}. Juntos, já têm o essencial."],
  mercury: {
    retro: [
      "Mercúrio está retrógrado e, segundo a tradição, é fase de mensagens mal entendidas. Truque: antes de ficar chateado, perguntem 'o que você quis dizer?'.",
      "Com Mercúrio retrógrado, diz a tradição, é tempo de reler antes de enviar e de confirmar o combinado. Nada que um bom 'combinado?' não resolva.",
      "Mercúrio de ré: segundo a tradição, assuntos antigos voltam à conversa. Se aparecer um, tratem com leveza.",
      "Dizem que, com Mercúrio retrógrado, objetos somem e horários confundem. Combinem rir da bagunça em vez de procurar culpado.",
    ],
    station: {
      retro: "Hoje Mercúrio começa a andar para trás: segundo a tradição, vale reler os combinados antes de seguir.",
      direct: "Hoje Mercúrio volta a andar para a frente: a conversa tende a ficar mais clara e os mal-entendidos, mais raros.",
    },
  },
  venus: {
    lead: "Vênus, o planeta do amor, está em {sign}: {t}.",
    items: ["o amor tem pressa e gosta de conquista, então tomem a iniciativa", "o amor é sensorial: toque, comida e cheiro bom", "o amor vem pela conversa e pelo humor", "o amor quer colo, casa e memória", "o amor quer brilho e declaração em voz alta", "o amor aparece nos pequenos cuidados", "o amor está elegante e harmonioso", "o amor fica intenso e sem meias palavras", "o amor quer liberdade e aventura a dois", "o amor é firme e constrói devagar", "o amor é amizade antes de tudo, e original", "o amor é romântico, sonhador e entregue"],
  },
  mars: {
    lead: "Marte, o planeta da energia e do desejo, está em {sign}: {t}.",
    items: ["energia de sobra e vontade de agir", "ritmo lento e firme, com prazer nos sentidos", "mente agitada, e a conversa é o melhor exercício", "o desejo vem pelo cuidado e pela segurança", "vontade de brilhar e de ser admirado", "energia para organizar, e vale dedicá-la também ao prazer", "o desejo pede harmonia e cortejo", "desejo intenso e magnético", "ânimo para passear e fazer esporte juntos", "energia disciplinada, boa para projetos a dois", "vontade de fazer coisas fora do comum", "energia suave, mais sonho do que ação"],
  },
  sun: {
    lead: "O Sol está em {sign}: estação de {t}.",
    items: ["recomeços e coragem", "prazeres simples e constância", "conversa e curiosidade", "casa e afeto", "calor e festa", "ordem e cuidado", "equilíbrio e parceria", "profundidade e mudança", "aventura e otimismo", "metas e compromisso", "novidade e amizade", "sonho e sensibilidade"],
  },
  gestures: {
    fire: ["Proponha algo novo para fazerem juntos hoje, por mais simples que seja.", "Faça um elogio em voz alta, sem motivo nenhum.", "Convide para uma caminhada de 15 minutos antes do jantar.", "Escolham um lugar para ver o pôr do sol e vão a pé.", "Desafie o outro para um jogo rápido, com um prêmio bobo para quem ganhar.", "Faça uma coisa que você sempre adia e dedique-a ao outro.", "Diga em voz alta três coisas que admira no outro.", "Dancem na cozinha enquanto o jantar cozinha.", "Troquem de lugar no sofá e vejam o dia do ponto de vista do outro.", "Planeje um mini-passeio surpresa para o fim de semana, mesmo que seja só até uma padaria diferente.", "Contem um para o outro o sonho mais maluco que já tiveram.", "Peça um conselho ao outro sobre algo pequeno e siga o conselho."],
    earth: ["Prepare algo com as mãos: um café, um lanche, uma mesa arrumada.", "Faça hoje uma tarefa que o outro detesta fazer.", "Deixe um bilhete curto onde o outro vai achar.", "Arrumem juntos um cantinho da casa que incomoda e comemorem com um chá.", "Cozinhem juntos uma receita simples que nenhum dos dois já fez.", "Massageie as mãos do outro por 3 minutos.", "Escreva num papel uma coisa que você agradece no outro e deixe no bolso do casaco.", "Passeiem descalços na grama ou no tapete e conversem sobre nada.", "Façam a cama juntos, devagar, como se fosse um ritual.", "Comprem uma planta ou uma flor e escolham um nome para ela.", "Deixe pronta a roupa do outro para amanhã, com carinho.", "Façam uma refeição sem celular, só vocês e o prato."],
    air: ["Mande uma mensagem 'lembrei de você porque…' com algo bem específico.", "Façam uma pergunta curiosa um ao outro e escutem a resposta inteira.", "Escolham uma música e dancem 3 minutos na sala.", "Troquem de playlist: cada um escolhe 3 músicas para o outro.", "Escreva um bilhete de 3 linhas e esconda num livro do outro.", "Façam um quiz de 5 perguntas sobre o dia em que se conheceram.", "Contem um para o outro o que pensaram quando se viram pela primeira vez.", "Inventem juntos um apelido novo e engraçado, que só vocês usem.", "Leiam em voz alta um trecho de livro, poema ou receita, e comentem.", "Tirem uma foto juntos fazendo careta e usem de papel de parede por um dia.", "Peça ao outro três palavras e escreva uma frase com elas.", "Contem um para o outro uma história boba da infância."],
    water: ["Abrace por 20 segundos, sem falar nada.", "Conte uma lembrança boa dos dois e peça que o outro conte a sua.", "Pergunte 'como você está de verdade?' e escute até o fim.", "Preparem um chá ou um banho quente para o outro, sem pedir nada em troca.", "Olhem fotos antigas dos dois e escolham a favorita.", "Escreva três linhas sobre como o outro faz você se sentir e entregue.", "Fiquem 5 minutos em silêncio, de mãos dadas.", "Ouçam juntos uma música que marcou a história de vocês.", "Façam uma lista de cinco lugares onde gostariam de acordar juntos.", "Escolham um filme antigo e vejam abraçados, sem comentar.", "Peça desculpas por algo pequeno que ficou pendente, com um abraço.", "Contem um para o outro o que mais gostam no cheiro, na voz ou no riso do outro."],
  },
  moonGestures: ["Comecem algo pequeno hoje, mesmo que seja só uma música nova na cozinha.", "Façam um jantar caprichado ou um lanche gostoso, bem devagar.", "Troquem 10 mensagens divertidas ao longo do dia, mesmo estando juntos.", "Faça um carinho no outro e pergunte: 'do que você precisa hoje?'.", "Façam um elogio caprichado, daqueles de plateia.", "Faça um favor discreto que o outro só vai notar mais tarde.", "Escolham juntos um programa e cada um cede em uma coisa.", "Olhem nos olhos por 30 segundos, sem falar, e depois contem o que sentiram.", "Mudem de caminho hoje: voltem para casa por uma rua que nunca usaram.", "Combinem uma meta pequena para o mês e marquem no calendário.", "Façam algo que nunca fizeram juntos, por menor que seja.", "Fiquem de conchinha por cinco minutos, em silêncio."],
  closings: [
    "Só diversão, mas o beijo é de verdade.",
    "Se der certo, a Lua leva o crédito. Se der errado, a culpa é de Mercúrio.",
    "Signo nenhum decide por vocês, mas ajuda a puxar assunto.",
    "O céu sugere; quem decide é o abraço.",
    "Hoje o horóscopo é só um pretexto para chegar mais perto.",
    "Se nada disso fizer sentido, ao menos vocês riram juntos.",
    "O universo não manda em vocês, mas aprecia a iniciativa.",
    "Pequenos gestos, grandes efeitos, e nenhum planeta precisa saber.",
    "Brinquem sem pressão: quem acerta ganha um beijo, quem erra também.",
    "Previsão do dia: probabilidade alta de carinho.",
    "As estrelas olham de longe; quem abraça é você.",
    "Leve a sério só o carinho; o resto é brincadeira.",
  ],
  chips: { moonIn: "Lua em {sign}", mercuryRetro: "Mercúrio retrógrado", mercuryDirect: "Mercúrio direto" },
};
