// Couple's horoscope text blocks (EN). Tone: a balance of romantic and funny.
export default {
  moon: [
    ["The Moon woke up in a hurry", "With the Moon in Aries, the day asks for initiative: whoever has an idea, say it now. Just don't let the rush trample the tenderness."],
    ["A day of good laziness and real affection", "With the Moon in Taurus, everything that feels good gets stronger: good food, the sofa, slow touch. Today comfort beats the plan."],
    ["The Moon is chatting away", "With the Moon in Gemini, the day is for talking, messaging and changing the subject every five minutes. Enjoy it: loose conversation is a couple's best seasoning."],
    ["Moon at home, heart wide open", "With the Moon in Cancer, hearts soften and home feels cosier. A day for cuddles, good memories and looking after the one you love."],
    ["The Moon wants applause (and a hug)", "With the Moon in Leo, you want to shine and be noticed. Today a sincere compliment is worth gold, and the giver wins too."],
    ["The Moon is tidying the house", "With the Moon in Virgo, the day is for details, for putting things in order and for showing love in small acts. But nobody has to be perfect to be loved."],
    ["A day to balance the scales together", "With the Moon in Libra, charm and harmony rise. A good day to decide together, to be romantic and to avoid silly arguments."],
    ["A deep Moon, a long look", "With the Moon in Scorpio, emotions run deep and glances last longer. A day for real conversation, the kind that gives a nice little shiver."],
    ["The Moon wants an adventure", "With the Moon in Sagittarius, you feel like leaving the routine, laughing out loud and saying yes to the unexpected. An improvised outing works wonders."],
    ["A serious Moon, a steady heart", "With the Moon in Capricorn, the day is for commitment and building slowly. Saying 'I'm here' is worth more than any speech."],
    ["A quirky Moon, just how you like it", "With the Moon in Aquarius, love turns original: no script, all surprise and friendship. Do something nobody else would."],
    ["A dreamy Moon, today daydreaming is allowed", "With the Moon in Pisces, imagination runs free and hearts get more tender. A day for music, for gazing out of the window and for speaking softly."],
  ],
  phases: [
    "The Moon is new: a great day to start over, make a wish and plant a small plan.",
    "The Moon is waxing: whatever you start now gains strength over the next few days.",
    "The Moon is at first quarter: time to take the step you were unsure about.",
    "The Moon is waxing gibbous, nearly full: energy rises, and so does the wish to do things together.",
    "The Moon is full: what was kept inside comes out, and feelings become clearer.",
    "The Moon begins to wane: a good moment to be thankful for what worked and let the rest go.",
    "The Moon is at last quarter: a day to let go of what weighs on you and simplify.",
    "The Moon is waning: it asks for rest, calm and quieter conversation.",
  ],
  phaseNames: ["New Moon", "Waxing crescent", "First quarter", "Waxing gibbous", "Full Moon", "Waning gibbous", "Last quarter", "Waning crescent"],
  events: {
    new: "Today is a New Moon in {sign}: a fresh start is in the air. Each of you makes one small wish for the month.",
    full: "Today is a Full Moon in {sign}: emotions come to the surface and everything looks clearer (and a bit more dramatic).",
    first: "Today is the first quarter in {sign}: a little push to take the plan off the paper.",
    last: "Today is the last quarter in {sign}: a day to let go of what weighs on you.",
  },
  aspects: [
    ["{A} and {B} share the same sign: you understand each other without subtitles, and you share the same flaws too. Today, laugh at the flaws twice as hard.", "Same sign, same habits (the good ones and the not-so-good). When you see yourself in the other, forgiving gets easy."],
    ["{A} and {B} are neighbouring signs, yet very different in style: one starts where the other ends. The fun is being curious about what is not like you.", "Neighbours in the zodiac and almost foreigners in temperament: {A} and {B} have a lot to show each other."],
    ["{A} and {B} have an easy affinity, the kind that only needs a little push. Today, give it the push.", "Between {A} and {B} things flow lightly. Just accept the invitation the other makes without noticing."],
    ["Between {A} and {B} there is a tasty tension that nudges and helps you grow. Today, treat the difference as seasoning, not as a flaw.", "{A} and {B} think differently, which is why the conversation never ends. Today, listen to the end before answering."],
    ["{A} and {B} flow together almost effortlessly. The only risk is autopilot: one new detail today makes all the difference.", "Between {A} and {B} there is a natural harmony. To avoid routine, do one little thing off-script."],
    ["{A} and {B} seem to speak different languages, and that is what makes the story interesting. Today, translate for each other, with patience and laughter.", "Between {A} and {B}, what one finds obvious the other never thought of. Asking 'why?' kindly solves almost everything."],
    ["{A} and {B} are opposites that complete each other: one has what the other lacks. Today, borrow what you don't have.", "Opposites attract, and {A} and {B} are the proof. Today's tip is to admire in the other exactly what you are not."],
  ],
  rulers: {
    mercury: "You both have Mercury as ruler, the planet of conversation: you speak the same language and understand each other through words.",
    venus: "You both have Venus as ruler, the planet of love and pleasure: you enjoy the same good things in life.",
    mars: "You both have Mars as ruler, the planet of energy: desire and drive go hand in hand.",
    jupiter: "You both have Jupiter as ruler, the planet of plenty and optimism: when you laugh, you laugh loudly.",
    saturn: "You both have Saturn as ruler, the planet of steadiness: you take commitment seriously and know how to wait.",
  },
  gives: ["the courage to begin", "calm and lasting affection", "conversation and curiosity", "care and emotional memory", "warmth and generosity", "attention to detail", "charm and a wish for harmony", "intensity and loyalty", "joy and a love of exploring", "firmness and constancy", "originality and freedom", "sensitivity and imagination"],
  givesLine: ["In today's mix, {A} brings {gA} and {B} brings {gB}.", "{A} offers {gA}; {B} offers {gB}. Together you already have the essentials."],
  mercury: {
    retro: [
      "Mercury is retrograde and, according to tradition, it is a time of misunderstood messages. Trick: before getting upset, ask 'what did you mean?'.",
      "With Mercury retrograde, tradition says, it is time to re-read before sending and to confirm what was agreed. Nothing a good 'agreed?' can't fix.",
      "Mercury in reverse: according to tradition, old topics come back into the conversation. If one shows up, handle it lightly.",
      "They say that with Mercury retrograde things go missing and schedules get muddled. Agree to laugh at the mess instead of looking for someone to blame.",
    ],
    station: {
      retro: "Today Mercury starts moving backwards: according to tradition, it is worth re-reading what you agreed before moving on.",
      direct: "Today Mercury moves forward again: conversation tends to get clearer and misunderstandings rarer.",
    },
  },
  venus: {
    lead: "Venus, the planet of love, is in {sign}: {t}.",
    items: ["love is in a hurry and likes the chase, so take the initiative", "love is sensual: touch, food and a lovely scent", "love comes through conversation and humour", "love wants cuddles, home and memories", "love wants sparkle and declarations out loud", "love shows in small acts of care", "love is elegant and harmonious", "love gets intense and speaks plainly", "love wants freedom and adventure for two", "love is steady and builds slowly", "love is friendship first, and original", "love is romantic, dreamy and wholehearted"],
  },
  mars: {
    lead: "Mars, the planet of energy and desire, is in {sign}: {t}.",
    items: ["plenty of energy and a wish to act", "a slow, steady pace with pleasure in the senses", "a busy mind, and conversation is the best exercise", "desire comes through care and security", "a wish to shine and be admired", "energy to organise, and worth spending on pleasure too", "desire asks for harmony and courtship", "intense, magnetic desire", "drive for outings and sport together", "disciplined energy, good for projects as a couple", "a wish to do out-of-the-ordinary things", "gentle energy, more dream than action"],
  },
  sun: {
    lead: "The Sun is in {sign}: the season of {t}.",
    items: ["fresh starts and courage", "simple pleasures and constancy", "conversation and curiosity", "home and affection", "warmth and celebration", "order and care", "balance and partnership", "depth and change", "adventure and optimism", "goals and commitment", "novelty and friendship", "dreams and sensitivity"],
  },
  gestures: {
    fire: ["Suggest something new to do together today, however simple.", "Pay a compliment out loud, for no reason at all.", "Invite them on a 15-minute walk before dinner.", "Pick a spot to watch the sunset and walk there.", "Challenge the other to a quick game, with a silly prize for the winner.", "Do something you always put off and dedicate it to the other.", "Say out loud three things you admire about the other.", "Dance in the kitchen while dinner cooks.", "Swap places on the sofa and see the day from the other's point of view.", "Plan a surprise mini-outing for the weekend, even if it is only to a different bakery.", "Tell each other the wildest dream you ever had.", "Ask the other for advice on something small and follow it."],
    earth: ["Make something with your hands: a coffee, a snack, a nicely laid table.", "Do a chore today that the other one hates doing.", "Leave a short note where the other will find it.", "Tidy a corner of the house that bothers you both, and celebrate with a cup of tea.", "Cook together a simple recipe neither of you has made.", "Massage the other's hands for 3 minutes.", "Write on a slip of paper something you are thankful for in the other and tuck it in their coat pocket.", "Walk barefoot on the grass or the rug and talk about nothing.", "Make the bed together, slowly, like a ritual.", "Buy a plant or a flower and choose a name for it.", "Lay out the other's clothes for tomorrow, with love.", "Have a meal with no phones, just the two of you and the plate."],
    air: ["Send a message saying 'I thought of you because…' with something very specific.", "Ask each other a curious question and listen to the whole answer.", "Pick a song and dance for 3 minutes in the living room.", "Swap playlists: each picks 3 songs for the other.", "Write a 3-line note and hide it in the other's book.", "Do a 5-question quiz about the day you met.", "Tell each other what you thought the first time you saw each other.", "Invent a new funny nickname that only you two use.", "Read aloud a passage from a book, a poem or a recipe, and comment on it.", "Take a photo together pulling silly faces and use it as your wallpaper for a day.", "Ask the other for three words and write a sentence with them.", "Tell each other a silly childhood story."],
    water: ["Hug for 20 seconds without saying anything.", "Tell a good memory of the two of you and ask the other to tell theirs.", "Ask 'how are you, really?' and listen to the end.", "Make a cup of tea or a hot bath for the other, asking nothing in return.", "Look at old photos of the two of you and pick a favourite.", "Write three lines about how the other makes you feel and hand them over.", "Sit for 5 minutes in silence, holding hands.", "Listen together to a song that marked your story.", "Make a list of five places where you would love to wake up together.", "Pick an old film and watch it cuddled up, without commenting.", "Apologise for something small that was left pending, with a hug.", "Tell each other what you like most about the other's scent, voice or laugh."],
  },
  moonGestures: ["Start something small today, even if it is just a new song in the kitchen.", "Make a lovingly prepared dinner or a tasty snack, very slowly.", "Trade 10 funny messages during the day, even if you are together.", "Give the other a caress and ask: 'what do you need today?'.", "Pay each other a well-crafted compliment, the grandstand kind.", "Do a discreet favour that the other will only notice later.", "Choose a plan together, and each of you gives way on one thing.", "Look into each other's eyes for 30 seconds, without speaking, then say what you felt.", "Change your route today: go home along a street you have never used.", "Agree on one small goal for the month and mark it on the calendar.", "Do something you have never done together, however small.", "Spoon for five minutes, in silence."],
  closings: [
    "Just for fun, but the kiss is real.",
    "If it works out, the Moon gets the credit. If it doesn't, blame Mercury.",
    "No sign decides for you, but it helps to start a conversation.",
    "The sky suggests; the hug decides.",
    "Today the horoscope is just an excuse to get closer.",
    "If none of this makes sense, at least you laughed together.",
    "The universe doesn't boss you around, but it appreciates the initiative.",
    "Small gestures, big effects, and no planet needs to know.",
    "Play without pressure: whoever guesses right gets a kiss, and so does whoever guesses wrong.",
    "Forecast for the day: high chance of tenderness.",
    "The stars look on from afar; the one hugging is you.",
    "Take only the affection seriously; the rest is play.",
  ],
  chips: { moonIn: "Moon in {sign}", mercuryRetro: "Mercury retrograde", mercuryDirect: "Mercury direct" },
};
