// Ideias noturnas extras do motor (variantes de execução com period: "night") e seus textos nos 3 idiomas.
// Formato do texto: [título, porquê, passos, detalhe, planB]
// Regras: sem preços, sem nomes de apps/marcas; tudo realista e seguro para a noite.
export const NIGHT_BASES = [
  { id: "V2-083", from: "V2-020", title: "Cidade acesa: um passeio à noite" },
  { id: "V2-084", from: "V2-029", title: "Noite de turistas na própria cidade" },
  { id: "V2-085", from: "V2-047", title: "Petiscos de rua ao anoitecer" },
  { id: "V2-086", from: "V2-022", title: "Mirante à noite" },
  { id: "V2-087", from: "V2-015", title: "Baile na sala à luz baixa" },
  { id: "V2-088", from: "V2-009", title: "Noite de playlist a dois" },
];

export const NIGHT_T = {
  pt: {
    "V2-083": ["Cidade acesa: um passeio à noite", "À noite a cidade muda de cara: luzes, vitrines e ruas mais calmas. É o cenário ideal para andar devagar e conversar.", ["Escolham uma rua ou bairro iluminado e movimentado o bastante para se sentirem à vontade.", "Saiam depois do jantar, de casacos leves, com os celulares guardados.", "Cada um escolhe uma luz, uma vitrine ou um cantinho que achou bonito e conta por quê.", "Parem num banco ou numa praça iluminada e fiquem um minuto em silêncio, só olhando.", "Voltem de mãos dadas, por outro caminho, sem pressa."], "Combinem antes o caminho de volta e fiquem em ruas iluminadas.", "Se chover, façam o mesmo passeio olhando a cidade da janela, com algo quente para beber."],
    "V2-084": ["Noite de turistas na própria cidade", "Ver a cidade à noite, como quem acabou de chegar, faz o comum parecer novo e rende conversa a noite toda.", ["Escolham 3 pontos da cidade que ficam bonitos à noite: uma praça, uma ponte, uma fachada iluminada.", "Façam o roteiro entre os pontos a pé, devagar, sem pressa.", "Em cada ponto, tirem uma foto juntos como se fossem turistas.", "Parem num lugar tranquilo para um chá, um café ou algo simples para dividir.", "Fechem a noite escolhendo qual dos 3 pontos foi o favorito e por quê."], "Levem um casaco a mais para o caso de esfriar e deixem a bateria do celular carregada.", "Se o tempo não ajudar, escolham só um dos pontos e terminem a noite em casa com as fotos."],
    "V2-085": ["Petiscos de rua ao anoitecer", "Comer em pé, andando e provando um pouco de tudo vira encontro sem cerimônia, com cheiro e clima de noite de cidade.", ["Escolham um bairro conhecido por suas barraquinhas, tascas ou lanchonetes populares.", "Cada um escolhe um petisco para o outro provar, sem dizer o que é antes.", "Dividam tudo: o ideal é provar pouco de muita coisa.", "Parem para comer num banco ou num muro, olhando o movimento.", "Terminem com algo doce e uma caminhada curta para digerir."], "Confirmem antes quais lugares estão abertos à noite.", "Se estiver tudo fechado, comprem algo simples e façam o mesmo jogo de provar às cegas em casa."],
    "V2-086": ["Mirante à noite", "Uma cidade vista de cima, com as luzes acesas, dá a sensação de ter o mundo inteiro ali, só para os dois.", ["Escolham um mirante, um alto ou uma praça com vista, de fácil acesso e boa iluminação.", "Cheguem ao anoitecer, para ver a luz mudar.", "Levem uma manta ou um casaco e algo quente para beber.", "Cada um conta um desejo para o próximo ano, em voz baixa.", "Fiquem até as luzes da cidade se acenderem por completo e voltem juntos, por um caminho iluminado."], "Contem em silêncio até 20 antes de falar de novo, só aproveitando a vista.", "Se o tempo fechar, escolham uma janela alta de casa e façam o mesmo ritual."],
    "V2-087": ["Baile na sala à luz baixa", "Dançar em casa à noite, sem plateia, tira a vergonha e dá um clima de encontro de verdade.", ["Apaguem a luz principal e deixem só uma luminária ou luzes pequenas.", "Escolham juntos 5 músicas lentas e 2 mais animadas.", "Afastem os móveis para abrir espaço no meio da sala.", "Dancem a primeira música bem juntinhos, de olhos fechados.", "Terminem com a música que marcou a história de vocês e um abraço longo."], "Troquem de par de sapatos pelas meias e dancem sem se preocupar com o passo certo.", "Se o espaço for pequeno, dancem na cozinha ou no corredor: o clima é o mesmo."],
    "V2-088": ["Noite de playlist a dois", "Cada um escolhe músicas para o outro, e cada música conta um pouco de quem escolheu. É conversa disfarçada de som.", ["Cada um separa 5 músicas pensando no outro: uma que lembra um momento, uma que faz rir, uma que dá saudade.", "Apaguem a luz principal e deixem só uma luz baixa, com cobertor e algo quente para beber.", "Alternem as músicas e, antes de cada uma, quem escolheu diz só uma frase sobre ela.", "Depois de ouvir, o outro conta o que sentiu.", "Fechem com uma música escolhida a dois."], "Guardem a lista e abram de novo daqui a um ano.", "Se faltar caixa de som, usem fones, um fone para cada um."],
  },
  en: {
    "V2-083": ["The city lit up: an evening stroll", "At night the city changes its face: lights, shop windows and quieter streets. It is the perfect setting for walking slowly and talking.", ["Pick a lit-up street or neighbourhood that is lively enough to feel comfortable.", "Head out after dinner in light jackets, phones put away.", "Each of you chooses a light, a window or a corner you found beautiful and says why.", "Stop on a bench or a lit square and stay quiet for a minute, just looking.", "Walk back hand in hand, by a different route, without hurry."], "Agree on the way back beforehand and stick to well-lit streets.", "If it rains, take the same walk with the city seen from the window and something warm to drink."],
    "V2-084": ["A night of tourists in your own city", "Seeing the city at night, like someone who has just arrived, makes the ordinary feel new and gives you things to talk about all evening.", ["Pick 3 spots in town that look good at night: a square, a bridge, a lit-up facade.", "Walk between them slowly, with no rush.", "At each spot, take a photo together as if you were tourists.", "Stop somewhere quiet for a tea, a coffee or something simple to share.", "End the night by choosing which of the 3 spots was your favourite and why."], "Take an extra layer in case it gets cold, and charge your phone.", "If the weather is bad, pick just one spot and finish the night at home with the photos."],
    "V2-085": ["Street snacks at dusk", "Eating on foot, tasting a little of everything, makes a date with no ceremony, full of the smells and mood of a city evening.", ["Choose a neighbourhood known for its stalls, small eateries or street food.", "Each picks a snack for the other to try without saying what it is first.", "Share everything: the idea is a little bit of many things.", "Stop on a bench or a low wall to eat and watch the world go by.", "Finish with something sweet and a short walk."], "Check beforehand which places are open in the evening.", "If everything is closed, buy something simple and play the same blind-tasting game at home."],
    "V2-086": ["A viewpoint at night", "A city seen from above with its lights on gives the feeling that the whole world is right there, just for the two of you.", ["Pick a viewpoint, a high spot or a square with a view that is easy to reach and well lit.", "Arrive at dusk to watch the light change.", "Bring a blanket or a jacket and something warm to drink.", "Each tells the other a wish for the coming year, in a low voice.", "Stay until the city lights are fully on and walk back together by a lit route."], "Stay silent for a count of 20 before you speak again, just enjoying the view.", "If the weather turns, pick a high window at home and do the same ritual."],
    "V2-087": ["A dance in the living room, low light", "Dancing at home at night, with no audience, melts the shyness and feels like a real date.", ["Switch off the main light and leave just a lamp or small lights on.", "Choose together 5 slow songs and 2 livelier ones.", "Push the furniture aside to make room in the middle.", "Dance the first song very close, eyes closed.", "Finish with the song that marked your story and a long hug."], "Dance in socks and forget about the right steps.", "If space is tight, dance in the kitchen or the hallway: the mood is the same."],
    "V2-088": ["A playlist night for two", "Each of you picks songs for the other, and every song says something about who chose it. It is conversation disguised as sound.", ["Each prepares 5 songs with the other in mind: one that recalls a moment, one that makes you laugh, one that brings longing.", "Switch off the main light, leaving a low one on, with a blanket and something warm to drink.", "Take turns, and before each song the chooser says just one sentence about it.", "After listening, the other says what they felt.", "End with a song you pick together."], "Keep the list and open it again in a year.", "If you have no speaker, share a pair of headphones, one earbud each."],
  },
  es: {
    "V2-083": ["La ciudad iluminada: un paseo nocturno", "De noche la ciudad cambia de cara: luces, escaparates y calles más tranquilas. Es el escenario ideal para caminar despacio y hablar.", ["Elegid una calle o un barrio iluminado y con la animación justa para sentiros a gusto.", "Salid después de cenar, con chaquetas ligeras y los móviles guardados.", "Cada uno elige una luz, un escaparate o un rincón que le haya parecido bonito y cuenta por qué.", "Parad en un banco o en una plaza iluminada y quedaos un minuto en silencio, solo mirando.", "Volved de la mano, por otro camino, sin prisa."], "Acordad antes el camino de vuelta y quedaos en calles bien iluminadas.", "Si llueve, haced el mismo paseo mirando la ciudad desde la ventana, con algo calentito para beber."],
    "V2-084": ["Noche de turistas en vuestra propia ciudad", "Ver la ciudad de noche, como quien acaba de llegar, hace que lo corriente parezca nuevo y da conversación para toda la velada.", ["Elegid 3 puntos de la ciudad que queden bonitos de noche: una plaza, un puente, una fachada iluminada.", "Haced el recorrido entre ellos a pie, despacio, sin prisa.", "En cada punto, haceos una foto juntos como si fuerais turistas.", "Parad en un sitio tranquilo para tomar un té, un café o algo sencillo para compartir.", "Cerrad la noche eligiendo cuál de los 3 puntos fue el favorito y por qué."], "Llevad una capa más por si refresca y dejad el móvil cargado.", "Si el tiempo no acompaña, quedaos con un solo punto y acabad la noche en casa con las fotos."],
    "V2-085": ["Tapeo callejero al anochecer", "Comer de pie, caminando y probando un poco de todo es una cita sin ceremonias, con los olores y el ambiente de una noche de ciudad.", ["Elegid un barrio conocido por sus puestos, bares pequeños o comida callejera.", "Cada uno elige un bocado para que el otro lo pruebe sin decir antes qué es.", "Compartid todo: lo ideal es probar un poco de muchas cosas.", "Parad a comer en un banco o en un murete, mirando el movimiento.", "Terminad con algo dulce y un paseo corto."], "Comprobad antes qué sitios están abiertos por la noche.", "Si todo está cerrado, comprad algo sencillo y jugad en casa al mismo juego de probar a ciegas."],
    "V2-086": ["Un mirador de noche", "Una ciudad vista desde arriba con las luces encendidas da la sensación de tener el mundo entero ahí, solo para vosotros dos.", ["Elegid un mirador, un alto o una plaza con vistas, de fácil acceso y bien iluminada.", "Llegad al anochecer para ver cómo cambia la luz.", "Llevad una manta o una chaqueta y algo caliente para beber.", "Cada uno cuenta un deseo para el próximo año, en voz baja.", "Quedaos hasta que las luces de la ciudad estén del todo encendidas y volved juntos por un camino iluminado."], "Contad en silencio hasta 20 antes de volver a hablar, solo disfrutando de la vista.", "Si el tiempo se estropea, elegid una ventana alta de casa y haced el mismo ritual."],
    "V2-087": ["Baile en el salón con luz tenue", "Bailar en casa de noche, sin público, quita la vergüenza y se siente como una cita de verdad.", ["Apagad la luz principal y dejad solo una lámpara o lucecitas.", "Elegid juntos 5 canciones lentas y 2 más animadas.", "Apartad los muebles para hacer sitio en el centro.", "Bailad la primera canción muy juntitos, con los ojos cerrados.", "Terminad con la canción que marcó vuestra historia y un abrazo largo."], "Bailad en calcetines y olvidaos de los pasos correctos.", "Si hay poco espacio, bailad en la cocina o en el pasillo: el ambiente es el mismo."],
    "V2-088": ["Noche de playlist para dos", "Cada uno elige canciones para el otro y cada canción cuenta algo de quien la eligió. Es conversación disfrazada de sonido.", ["Cada uno prepara 5 canciones pensando en el otro: una que recuerda un momento, una que hace reír, una que da morriña.", "Apagad la luz principal y dejad una tenue, con una manta y algo caliente para beber.", "Id alternando y, antes de cada canción, quien la eligió dice solo una frase sobre ella.", "Después de escucharla, el otro cuenta lo que sintió.", "Cerrad con una canción elegida entre los dos."], "Guardad la lista y volved a abrirla dentro de un año.", "Si no tenéis altavoz, compartid unos auriculares, uno para cada uno."],
  },
};
