// Textos editoriais do motor de ideias (português do Brasil).
// O motor (recommendations.mjs) decide QUAL ideia combina com os filtros, com as regras de segurança,
// custo e tempo dos arquivos de autoridade. Este arquivo só troca o TEXTO mostrado ao visitante.
// Chave: "<familyId>@<minutos>" ou o id da variante (V2-0xx). Formato: [título, porquê, passos, detalhe, planB?]
export const T = {
  // ───────── EM CASA · 1 hora ─────────
  "JOG-01@75": ["Noite de tabuleiro, com aposta carinhosa", "Um jogo simples já tem tudo: risada, provocação boa e a atenção inteira nos dois. Cabe numa hora e não custa nada.", ["Escolham um jogo que já tenham em casa (ou o que estiver mais empoeirado na prateleira).", "Combinem uma aposta carinhosa: quem perder faz o próximo café, uma massagem de 5 minutos ou escolhe a próxima música.", "Arrumem a mesa com uma luz mais baixa e algo para beliscar.", "Guardem os celulares longe, em outro cômodo.", "Joguem uma partida só, com calma, e comemorem o resultado como se fosse final de campeonato.", "Cumpram a aposta com capricho."], "Deixem uma pequena escolha para quem perdeu: ele ou ela decide a sobremesa."],
  "JOG-02@75": ["Rodada de cartas valendo um carinho", "Um baralho cabe em qualquer bolso e rende uma hora de conversa leve, sem preparação nenhuma.", ["Peguem um baralho (qualquer jogo vale: truco, buraco, rouba-monte, pôquer de brincadeira).", "Antes de começar, combinem o prêmio: o vencedor de cada rodada pede um pequeno gesto, como um abraço de 20 segundos ou um elogio sincero.", "Sentem frente a frente, com uma bebida quente ou gelada por perto.", "Joguem algumas rodadas rápidas, sem pressa para terminar.", "Na última rodada, quem ganhar escolhe uma lembrança boa para os dois contarem."], "Cada vitória vale um elogio específico, nada genérico."],
  "MUS-08@75": ["Karaokê na sala, sem vergonha nenhuma", "Cantar junto derruba a timidez e faz qualquer terça-feira virar festa pequena. Basta o celular e uma caixa de som (ou só a TV).", ["Abram um vídeo de karaokê no celular ou na TV (há muitos gratuitos).", "Montem uma lista de 5 músicas: duas que um escolhe, duas que o outro escolhe e uma que cantem em dupla.", "Apaguem a luz principal e deixem só uma luminária ou luzes de enfeite.", "Cantem a primeira sem se importar com a nota; quem errar mais paga um beijo de consolação.", "Terminem com a música dos dois, aquela que vocês cantariam até desafinando."], "Escolham a última música juntos, sem veto."],
  // ───────── EM CASA · 1 hora · surpresa ─────────
  "MUS-03@75": ["A trilha sonora da nossa história", "Músicas guardam memórias que a gente nem sabe que tem. Escutar com atenção, sem tela, aproxima.", ["Antes do encontro, separe 4 ou 5 músicas ligadas a momentos dos dois: a primeira viagem, a música do casamento, uma que fala de vocês.", "Prepare o lugar: uma luz suave, um cobertor e algo gostoso para beber.", "Convide a pessoa a sentar e escutar de olhos fechados, sem celular.", "Depois de cada música, peça que conte a primeira lembrança que veio à cabeça.", "No fim, deixe a última música ser uma que vocês nunca ouviram juntos e que você escolheu pensando nela."], "Escreva num papelzinho por que escolheu cada música e entregue no final."],
  "JOG-04@75": ["Quiz: quanto a gente sabe um do outro?", "É um jogo que vira conversa sem esforço: as respostas certas e erradas rendem as melhores risadas.", ["Escreva em segredo 8 perguntas sobre vocês: primeira impressão, comida favorita, sonho antigo, medo bobo.", "Cada um responde no papel o que acha que o outro respondeu e depois confere.", "Combinem pontos: 1 por acerto e 2 se acertar a pergunta bônus.", "Deixem a rodada final para uma pergunta que nenhum dos dois saiba responder, e inventem a resposta juntos.", "O perdedor faz um pedido pequeno ao vencedor."], "Façam pelo menos uma pergunta sobre algo que mudou em vocês neste ano."],
  "ART-11@75": ["Um cantinho da casa decorado em segredo", "Transformar um canto comum em cenário romântico, com o que já existe em casa, é uma surpresa que se vê e se sente.", ["Escolha um canto da casa: o sofá, a varanda, a mesa da cozinha ou o quarto.", "Reúna o que já tem: velas ou lâmpadas amareladas, almofadas, lençóis, flores ou folhas, fotos de vocês.", "Monte o cenário enquanto a pessoa está fora ou ocupada, com música baixa de fundo.", "Deixe um bilhete curto no centro, convidando a pessoa a ficar ali com você.", "Aproveitem o cantinho com algo gostoso para beliscar, sem celular."], "Tire uma foto do cantinho antes de desmontar, para lembrar."],
  // ───────── EM CASA · 1 hora · reconectar ─────────
  "VIN-07@75": ["Voltar ao dia em que tudo começou", "Rever uma lembrança boa a dois lembra por que vocês se escolheram. Só pede atenção e vontade.", ["Escolham uma lembrança querida: o primeiro encontro, uma viagem, um dia de chuva.", "Sentem sem celular e contem, um de cada vez, o que lembram em detalhes: cheiros, roupas, o que sentiram.", "Procurem uma foto ou um objeto daquele dia e coloquem entre vocês.", "Cada um diga uma coisa que ainda continua verdade hoje.", "Terminem escolhendo uma pequena lembrança nova para criar nesta semana."], "Guardem o objeto ou a foto num lugar visível por alguns dias."],
  "VIN-09@75": ["Meia hora de gratidão, com abraço no final", "Dizer em voz alta o que a gente agradece muda o clima da casa inteira, e custa só atenção.", ["Sentem juntos em um lugar confortável, sem televisão e sem celular.", "Cada um escreve 3 coisas que agradece no outro: uma pequena do dia a dia, uma que mudou sua vida, uma que nunca tinha dito.", "Leiam as listas devagar, um de cada vez, olhando nos olhos.", "Depois de cada item, o outro responde apenas \"obrigado(a)\" e espera um instante.", "Fechem com um abraço sem pressa."], "Guardem as listas para ler de novo daqui a um ano."],
  "MUS-04@75": ["Playlist a dois, uma música por vez", "Montar uma playlist em conjunto é uma conversa disfarçada: cada música é um recado.", ["Criem uma playlist nova em algum aplicativo gratuito de música.", "Cada um adiciona uma música por vez e explica por que escolheu.", "Façam 6 a 8 rodadas, sem repetir artista.", "Ouçam a playlist inteira, sem celular na mão, dançando ou apenas deitados.", "Deem um nome para ela que só vocês dois entendam."], "A última música da playlist será a da primeira rodada, tocada de novo no fim."],
  // ───────── EM CASA · tarde ─────────
  "JOG-03@240": ["Tarde de quebra-cabeça com chá e conversa", "Montar um puzzle juntos é um programa lento e calmo, daqueles em que a conversa vai surgindo sozinha.", ["Escolham um puzzle que já tenham em casa (ou montem um dos mais simples).", "Preparem uma mesa ampla, uma boa luz e uma bebida quente ou gelada.", "Separem as bordas primeiro e montem a moldura juntos.", "A cada meia hora, façam uma pausa para alongar e comer algo.", "Quem encaixar a última peça faz um brinde ou conta uma lembrança boa."], "Combinem de antemão que não vale correr: o objetivo é a tarde, não o puzzle pronto."],
  "ART-01@240": ["Tarde de arte livre: o retrato do outro", "Desenhar sem saber desenhar é o melhor tipo de brincadeira: o resultado importa menos que o riso.", ["Reúnam papel, lápis ou o que houver (até caneta e giz de cera).", "Sentem frente a frente e desenhem o outro por 15 minutos, sem apagar.", "Troquem os desenhos e cada um escreve uma frase carinhosa no verso.", "Façam um segundo desenho juntos, no mesmo papel, cada um com uma cor.", "Montem um pequeno mural improvisado com as obras na parede."], "Assinem as obras e deem um título engraçado a cada uma."],
  "COM-01@240": ["Uma tarde de bondade a dois, sem sair de casa", "Fazer algo bom por alguém aproxima e deixa a gente leve. Dá para ajudar mesmo de dentro de casa.", ["Escolham uma causa simples: separar roupas e livros que podem ser doados, escrever cartões para alguém que está só, preparar uma refeição para um vizinho.", "Dividam as tarefas e coloquem uma música agradável para tocar.", "Façam tudo com calma e conversem sobre quem vai receber aquilo.", "Fechem com algo gostoso feito por vocês.", "Combinem quando e como entregar ou doar."], "Deixem um bilhete anônimo e carinhoso junto com a doação."],
  "GAS-08@240": ["Sobremesa feita por vocês, do início ao fim", "Cozinhar algo doce juntos é um programa que termina com recompensa e cheiro bom na casa.", ["Escolham uma sobremesa simples: brigadeiro, bolo de caneca, pudim, frutas com chocolate.", "Separem os ingredientes e dividam as tarefas: um mistura, o outro cuida do fogo ou do forno.", "Coloquem uma playlist leve e cozinhem sem pressa.", "Deixem esfriar enquanto assistem a algo curto ou conversam.", "Sirvam em pratos bonitos e comam à luz de velas ou de uma lâmpada amarela."], "Mandem uma fatia para um vizinho ou amigo, sem avisar."],
  "ART-08@240": ["Colagem a dois com recortes e memórias", "Recortar e colar é um passatempo simples que acaba virando um pequeno presente para vocês.", ["Juntem revistas velhas, folhetos, papéis de embrulho, fotos que possam ser recortadas.", "Cada um escolhe uma palavra que descreve o casal e procura imagens que a representem.", "Montem uma colagem em conjunto numa folha grande.", "Escrevam uma frase curta no centro com as palavras que escolheram.", "Colem na parede ou na porta do armário, onde o casal passa todo dia."], "Deixem um cantinho em branco para acrescentar algo no próximo aniversário de namoro."],
  "MUS-06@240": ["Baile em casa, com direito a coreografia", "Dançar na sala é um jeito antigo de se aproximar e de espantar o cansaço. Não precisa saber dançar.", ["Montem uma playlist com 10 músicas de estilos diferentes: lenta, animada, nostálgica, engraçada.", "Afastem os móveis para abrir espaço e baixem a luz.", "Dancem a primeira música no estilo mais bobo que conseguirem.", "Inventem uma coreografia de 30 segundos para uma das músicas.", "Façam uma pausa com água e algo para beliscar e voltem para uma lenta.", "Terminem de rosto colado, escutando a última música sem se mexer muito."], "Gravem 15 segundos de vídeo só para vocês."],
  "ART-09@240": ["Montar o nosso álbum físico", "Fotos na tela se perdem. Um álbum em papel vira objeto que a gente folheia e mostra.", ["Escolham 15 ou 20 fotos digitais ou impressas dos momentos que mais marcaram vocês.", "Se tiverem impressora, imprimam; se não, usem recortes, ingressos, bilhetes ou desenhos.", "Colem em um caderno ou em folhas dobradas.", "Escrevam uma frase embaixo de cada foto.", "Reservem a última página para algo ainda por viver."], "Escrevam na capa uma data e uma frase que só vocês entendem."],
  "ART-10@240": ["Curadoria das fotos que contam a nossa vida", "Escolher as melhores fotos junto é revisitar a história e decidir qual parte vocês querem lembrar.", ["Abram a galeria do celular e separem as 30 fotos que mais gostam dos dois.", "Reduzam para 10, discutindo e justificando cada escolha.", "Imprimam as finalistas ou desenhem molduras de papel.", "Montem uma pequena exposição na parede ou numa mesa.", "Deem a cada foto um título curto."], "Escolham uma foto para mandar a alguém que importa para vocês."],
  "GAS-07@240": ["Cozinhar junto um prato que nenhum dos dois conhece", "Aprender algo novo a dois, com as mãos na massa, cria uma tarde que termina com jantar e história.", ["Escolham uma receita nova com ingredientes que consigam conseguir sem esforço.", "Divida as tarefas: um prepara os cortes e o outro cuida do fogo.", "Coloquem uma playlist e cozinhem sem pressa.", "Provem durante o preparo e ajustem o tempero juntos.", "Sirvam em uma mesa arrumada, sem celular, e contem como foi a experiência."], "Anotem a receita e a data para repetir daqui a um ano."],
  // ───────── AO AR LIVRE · 1 hora ─────────
  "NAT-01@75": ["Caminhada devagar, sem destino e com conversa", "Andar lado a lado ajuda a falar do que importa, sem aquele olho no olho que trava. É grátis e faz bem.", ["Escolham um parque, uma beira de rio, uma rua arborizada ou uma trilha curta perto de casa.", "Deixem os celulares no bolso e saiam sem pressa.", "Parem em um ponto bonito e fiquem em silêncio por 1 minuto, só olhando.", "Conversem sobre um sonho pequeno que cada um tem para este ano.", "Voltem por outro caminho, mesmo que seja mais longo."], "Levem uma garrafa de água e uma fruta para dividir."],
  "CID-01@75": ["Turistas na nossa própria cidade", "A cidade esconde cantos que a gente nunca olha. Olhar com olhos de turista muda o clima do passeio.", ["Escolham um bairro ou uma rua que nunca exploraram.", "Saiam a pé ou de transporte público e caminhem com os olhos para cima, notando fachadas e detalhes.", "Parem em 3 lugares e fotografem juntos, como fariam numa viagem.", "Sentem em um banco ou na escada de uma praça e comentem o que mais chamou a atenção.", "Escolham juntos a foto do dia."], "Levem um caderninho para anotar o nome dos lugares que quiserem rever."],
  "NAT-10@75": ["Uma hora de olhar para a natureza", "Observar pássaros, folhas, insetos e nuvens acalma e rende conversa. Não precisa saber nada.", ["Escolham um parque, jardim ou área verde que fique perto.", "Cada um escolhe 3 coisas que quer encontrar: um pássaro, uma flor, uma folha diferente.", "Andem devagar, em silêncio, e apontem o que acharem.", "Sentem em um banco e comparem o que encontraram.", "Quem achou algo mais curioso conta o que imaginou sobre aquilo."], "Fotografem um detalhe pequeno que muita gente passaria sem ver."],
  // ───────── AO AR LIVRE · 1 hora · surpresa ─────────
  "NAT-08@75": ["Um pôr do sol que um preparou em segredo", "Chegar a um lugar bonito com a pessoa de olhos vendados pelo cuidado é uma surpresa simples e grande.", ["Descubra um lugar com vista boa e fácil de chegar: mirante, beira-rio, praça alta.", "Confira a hora do pôr do sol e planeje chegar com 15 minutos de antecedência.", "Convide a pessoa com uma frase misteriosa, sem dizer onde vão.", "Leve uma manta, uma bebida e algo pequeno para comer.", "Fiquem em silêncio durante os últimos minutos de sol.", "Aproveitem a luz dourada para tirar uma foto juntos."], "Leve um bilhete curto para ler ali, quando o sol estiver quase sumindo."],
  "TEM-01@75": ["Olhar o céu à noite, com um mapa de estrelas", "Ver estrelas junto lembra o tamanho do mundo e aproxima. Um aplicativo gratuito ajuda a reconhecer as constelações.", ["Escolham uma noite sem muita nuvem e um lugar com pouca luz: parque, terraço, praia, praça.", "Levem uma manta e uma bebida quente.", "Baixem um aplicativo de mapa estelar antes de sair.", "Deitem ou sentem, apaguem as telas e deixem os olhos se acostumarem por uns 10 minutos.", "Identifiquem uma constelação e inventem uma história para ela."], "Peçam um desejo juntos, em voz baixa, e guardem em segredo."],
  "V2-024": ["Passear numa loja diferente, sem pressão de comprar", "Lojas pequenas e curiosas são museus gratuitos: discos, plantas, artesanato, livros usados.", ["Escolham uma loja de bairro diferente do comum: disco usado, artesanato, plantas, quinquilharias.", "Entrem sem obrigação de comprar nada e passeiem separados por 10 minutos.", "Cada um escolhe um objeto que o faz pensar no outro e mostra, sem comprar.", "Contem por que escolheram aquela peça.", "Saiam e parem em um banco ou café para conversar sobre o que viram."], "Não precisam comprar nada: o programa é olhar, imaginar e escolher o achado do dia."],
  // ───────── AO AR LIVRE · 1 hora · reconectar ─────────
  "NAT-05@75": ["Beira-mar para conversar de verdade", "O mar convida ao silêncio e à conversa sem pressa. O programa pede só chegar, sentar e escutar.", ["Escolham uma praia ou beira de água próxima e uma hora de pouco movimento.", "Deixem o celular guardado e caminhem na beira, descalços se o lugar permitir.", "Sentem na areia ou numa pedra e escutem as ondas por alguns minutos.", "Cada um conta uma coisa que está carregando e precisa de colo.", "Escrevam na areia uma palavra que descreva o que querem para os próximos meses."], "Levem uma toalha pequena para sentar."],
  "NAT-12@75": ["Colher o que a estação oferece", "Em lugares onde é permitido colher, catar frutas, folhas ou flores vira uma pequena aventura que dá presente no final.", ["Pesquisem um local permitido para colher: horta comunitária, pomar aberto, jardim com autorização.", "Confirmem regras e horários antes de sair.", "Levem uma sacola e uma tesourinha limpa.", "Colham só o que for permitido, com cuidado e respeito.", "Voltem e montem um pequeno buquê ou um lanche com o que colheram."], "Dê o buquê ou um pedacinho da colheita a alguém que goste de vocês."],
  "NAT-09@75": ["Um trilho leve, só para respirar junto", "Uma trilha curta e fácil reúne movimento, ar puro e conversa sem esforço.", ["Escolham um trilho curto e bem sinalizado, perto de onde moram.", "Confirmem a previsão do tempo e levem água e calçado adequado.", "Caminhem num ritmo em que dê para conversar.", "Parem em um ponto bonito e façam uma pausa de 5 minutos em silêncio.", "No fim, contem um momento do trajeto que vão lembrar."], "Levem um saquinho para recolher qualquer lixo que encontrarem."],
  // ───────── AO AR LIVRE · tarde ─────────
  "NAT-01@240": ["Tarde de caminhada, com paradas e lanche", "Uma tarde inteira ao ar livre muda o humor de qualquer um. Basta um bom caminho e paradas bem escolhidas.", ["Escolham uma rota de 1 a 2 horas de caminhada tranquila, com pontos bonitos.", "Levem água, lanche leve e um casaco extra.", "Façam duas ou três paradas: uma para fotografar, uma para lanchar, uma para ficar em silêncio.", "Contem uma história de infância em cada parada.", "Terminem tomando algo quente ou gelado num lugar simples."], "Escolham juntos um ponto do caminho para voltar numa outra estação do ano."],
  "CID-01@240": ["Tarde de turistas com um mapa feito por vocês", "Explorar a cidade com um roteiro inventado pelos dois vira uma pequena viagem.", ["Escolham 3 ou 4 pontos de um bairro novo: uma praça, uma rua com murais, um mercado, um mirante.", "Desenhem num papel um mapinha do passeio.", "Caminhem de um ponto a outro conversando e tirando fotos.", "Em cada ponto, cada um faz uma pergunta curta ao outro.", "Fechem a tarde com algo simples para comer."], "Colem o mapa num caderno e anotem o dia."],
  "NAT-10@240": ["Uma tarde para ver a natureza de perto", "Observar a natureza sem pressa devolve a calma. A tarde passa leve e rende conversa.", ["Escolham um parque grande, jardim botânico gratuito ou área verde.", "Levem lanche, água e uma manta.", "Percorram os caminhos e procurem animais, flores e árvores diferentes.", "Sentem no gramado e leiam ou desenhem por uma hora.", "Voltem andando devagar, comparando o que mais gostaram."], "Cada um escolhe a árvore preferida e conta por quê."],
  // ───────── AO AR LIVRE · tarde · surpresa ─────────
  "NAT-08@240": ["Tarde com vista, preparada em segredo", "Um lugar bonito, uma manta e uma pessoa que cuidou de tudo: é um jeito simples de dizer 'pensei em você'.", ["Descubra um lugar com vista boa, de fácil acesso.", "Prepare uma cesta pequena com algo para comer e beber, uma manta e um bilhete.", "Convide a pessoa com uma frase misteriosa, sem dizer onde vão.", "Chegando, estendam a manta e fiquem sem pressa olhando a paisagem.", "Entregue o bilhete e leiam juntos.", "Fiquem até a luz mudar."], "Levem um fone dividido para ouvir uma música dedicada."],
  "TEM-01@240": ["Entardecer e estrelas na mesma saída", "Ver o dia virar noite junto é uma sequência perfeita: pôr do sol, luz que some, primeiras estrelas.", ["Escolham um lugar aberto e seguro, longe de muita luz.", "Cheguem pouco antes do pôr do sol com manta, casaco e uma bebida quente.", "Vejam o sol se pôr e esperem o céu escurecer.", "Usem um aplicativo de estrelas para reconhecer planetas e constelações.", "Contem um desejo que ainda não contaram a ninguém."], "Voltem em silêncio parte do caminho, ainda com o céu na cabeça."],
  "CID-10@240": ["Tarde de lojinhas e curiosidades", "Uma tarde passeando por lojas pequenas e inesperadas vira uma caça ao tesouro sem custo.", ["Escolham um bairro com lojas de rua: sebos, discos, plantas, artesanato, brechós.", "Combinem que ninguém precisa comprar nada.", "A cada loja, cada um escolhe um objeto que descreve o outro e conta por quê.", "Parem para um café ou um suco quando cansarem.", "No fim, escolham o objeto mais curioso do dia e fotografem."], "Anotem o nome das lojas que quiserem visitar de novo."],
  // ───────── AO AR LIVRE · tarde · reconectar ─────────
  "NAT-05@240": ["Tarde de praia, sem agenda", "Passar a tarde junto no mar é desacelerar na prática. Basta chegar, sentar e deixar o tempo andar.", ["Escolham uma praia tranquila e um horário de pouco movimento.", "Levem toalha, protetor solar, água e um lanche simples.", "Caminhem na beira da água, conversando sobre algo que ficou parado entre vocês.", "Deitem na toalha e fiquem em silêncio por 10 minutos.", "Vejam o pôr do sol, se o horário permitir."], "Escrevam na areia um recado para o outro, e fotografem antes de a onda levar."],
  "NAT-12@240": ["Tarde de colheita e mesa feita a dois", "Colher, escolher e preparar junto fecha o ciclo: do pé ao prato, em uma tarde só.", ["Escolham um local onde a colheita seja permitida: horta comunitária, pomar aberto, feira de produtor com colheita.", "Confirmem regras e horários e levem sacola e luvas.", "Colham com cuidado e com respeito pelo lugar.", "Voltem e cozinhem algo simples com o que colheram.", "Comam à mesa, devagar, sem tela."], "Guardem uma semente ou uma folha para colar num caderno."],
  "NAT-09@240": ["Trilho leve com piquenique no meio do caminho", "Caminhar uma trilha fácil e parar para comer no meio dela é um programa que cabe numa tarde e fica na memória.", ["Escolham um trilho leve e bem sinalizado e confirmem o horário de funcionamento.", "Levem lanche, água, protetor e casaco.", "Caminhem em um ritmo de conversa.", "Parem num ponto bonito e comam sem pressa.", "Voltem sem correr e fechem com algo gostoso."], "Levem um saco para recolher o lixo que encontrarem pelo caminho."],
  // ───────── DIA INTEIRO · fora ─────────
  "VIA-01@420": ["Um dia inteiro de passeio por perto", "Um dia de passeio é pequeno demais para ser viagem e grande demais para ser rotina: é o ponto certo.", ["Escolham uma cidade ou região próxima que consigam visitar e voltar no mesmo dia.", "Confirmem horários, trajetos e bilhetes antes de sair.", "Saiam cedo, com água e lanche leve na mochila.", "Dividam o dia em três momentos: manhã de explorar, almoço sem pressa, tarde livre.", "Escolham um lugar para ver o pôr do sol antes de voltar.", "No caminho de volta, contem o que mais gostaram."], "Comprem uma lembrança pequena e simples do lugar."],
  "VIA-02@420": ["Dia de trem: ir longe sem sair do dia", "Viajar de trem tem charme próprio: a janela vira filme e a conversa corre solta.", ["Escolham um destino próximo, acessível de trem e com volta no mesmo dia.", "Confirmem horários e comprem os bilhetes com antecedência.", "No caminho de ida, sentem juntos à janela e comentem a paisagem.", "No destino, façam um passeio a pé e almocem em algo simples.", "Reservem a tarde para um lugar com vista ou uma praça.", "Na volta, descansem a cabeça um no ombro do outro."], "Escrevam um postal para si mesmos e guardem para ler depois."],
  "VIA-05@420": ["Um dia de balsa ou passeio panorâmico", "Ver a cidade ou a costa de dentro da água ou de cima muda a perspectiva de quem está junto.", ["Escolham um passeio de barco, balsa ou transporte panorâmico perto de onde moram.", "Confirmem horários e valores e vejam a previsão do tempo.", "Levem casaco, protetor solar e câmera ou celular carregado.", "Fiquem no convés ou à janela e identifiquem o que passam a ver.", "Desembarquem e explorem um pouco a área, com almoço sem pressa.", "Voltem na luz da tarde, se possível."], "Escolham juntos o ponto do trajeto que mais gostaram e fotografem."],
  // ───────── DIA INTEIRO · textos próprios por tipo de encontro (casual · surpresa · reconectar) ─────────
  "V2-037": ["Um dia de passeio por perto, sem roteiro e sem relógio", "Um dia fora de casa, sem hora marcada para nada, quebra a rotina sem exigir uma viagem de verdade.", ["Escolham uma cidade, vila ou praia a que dê para ir e voltar no mesmo dia.", "Confirmem horários de ida e volta e o valor dos bilhetes antes de sair.", "Combinem só duas coisas: onde almoçar e a hora do último transporte de volta.", "O resto vocês decidem no caminho, a cada esquina.", "Parem sempre que algo chamar a atenção, sem pressa de cumprir lista."], "Cada um escolhe uma parada surpresa para o outro durante o dia."],
  "V2-040": ["Um dia de passeio com um bilhete escondido no caminho", "O dia já é uma pequena viagem. Um bilhete que aparece na hora certa transforma o passeio em lembrança.", ["Escolham uma cidade, vila ou praia próxima, com volta no mesmo dia.", "Sem o outro ver, escreva um bilhete curto e específico sobre algo que só vocês dois viveram (nada de frase pronta).", "Esconda o bilhete na mochila, no casaco ou no livro da viagem e deixe para o momento certo: no almoço ou na hora do pôr do sol.", "Quando o outro ler, não expliquem nada. Deixem o silêncio fazer o trabalho."], "Escrevam à mão: a letra de quem escreve vale mais que a frase."],
  "V2-043": ["Um dia fora para ter a conversa que ficou para depois", "Quando a rotina engole as conversas importantes, um dia longe de casa devolve espaço para elas.", ["Escolham um destino próximo, tranquilo e com volta no mesmo dia.", "Combinem de antemão uma regra simples: sem celular no almoço e no caminho de ida.", "Façam um passeio a pé e deixem a conversa vir devagar, sem pauta.", "No almoço, cada um conta um momento do último ano de que sente falta.", "Antes de voltar, escolham algo pequeno para fazer juntos na semana seguinte."], "Anotem a ideia no celular, para não depender da memória."],
  "V2-064": ["Cidade vizinha com museu, mercado e um café para descansar", "Um dia com cultura e comida bem escolhidas rende mais conversa do que uma maratona de pontos turísticos.", ["Escolham uma cidade próxima com algum museu ou mercado que despertem curiosidade nos dois.", "Confirmem horários de abertura, bilhetes e transporte de volta.", "Façam uma visita só de manhã (um museu ou um mercado, não os dois).", "Almocem em algo local, sem turistice, e deem uma volta a pé na parte da tarde.", "Terminem o dia em um café, contando o que mais gostaram."], "Cada um escolhe e compra uma lembrança pequena e simples para o outro."],
  "V2-067": ["Dia fora com um bilhete para abrir à mesa do almoço", "Num dia longe de casa, um bilhete escondido faz o almoço comum virar a parte mais lembrada.", ["Escolham uma cidade próxima com almoço agradável e volta no mesmo dia.", "Escreva em segredo um bilhete curto, falando de algo específico que só vocês viveram.", "Entregue ao garçom, ou deixe sob o guardanapo, para ser lido quando sentarem à mesa.", "Passeiem a pé depois do almoço e deixem o bilhete render conversa."], "Escolham um lugar com mesa à janela, se der."],
  "V2-070": ["Dia fora de casa para voltar a se enxergar", "Um passeio longo, com tempo e sem tarefa, devolve ao casal o espaço de olhar um para o outro.", ["Escolham uma cidade próxima com museu, jardim ou mercado e volta no mesmo dia.", "Confirmem horários e bilhetes e saiam cedo.", "Façam a primeira hora de passeio em silêncio confortável, só olhando e apontando.", "No almoço, cada um diz três coisas que admira no outro, sem interromper.", "Na volta, falem do que ficou: o que querem repetir nos próximos meses."], "Troquem de lugar no transporte na volta: cada um vai com a vista do outro."],
  "V2-038": ["Viagem de trem para a primeira cidade que vocês escolherem", "O trajeto de trem já é metade do passeio: a janela vira filme e a conversa corre sem pressa.", ["Escolham uma cidade a que se chegue de trem e se volte no mesmo dia.", "Comprem os bilhetes com antecedência e conferam horários de ida e volta.", "Sentem lado a lado, de frente para a janela, e comentem a paisagem.", "No destino, façam um passeio a pé e almocem em algo simples.", "Voltem no fim da tarde, com a luz baixa."], "Levem um livro ou uma playlist para dividir no caminho: um fone para cada um."],
  "V2-041": ["Viagem de trem com uma música combinada para a janela", "O trem é o lugar perfeito para uma música dedicada: a paisagem passa e a canção diz o que vocês não precisam dizer.", ["Escolham uma cidade próxima, acessível de trem, com volta no mesmo dia.", "Escolha em segredo uma música que fale de vocês e prepare dois fones.", "Quando o trem sair, ofereça um fone e deixe tocar enquanto a paisagem passa.", "Digam, em uma frase, por que aquela música.", "Passeiem na cidade e deixem a música voltar à conversa."], "Guardem o nome da música no bilhete do trem."],
  "V2-044": ["Trem e conversa: um dia para escutar com atenção", "Num trem, ninguém tem para onde ir, e isso ajuda a falar o que ficou parado.", ["Escolham uma cidade a que se chegue de trem e se volte no mesmo dia.", "Combinem não usar o celular durante a viagem de ida.", "No trem, cada um conta um momento do último ano em que se sentiu muito próximo do outro.", "No destino, caminhem sem pressa e almocem em algo simples.", "Na volta, deixem o silêncio chegar sem forçar nada."], "Peguem o bilhete de ida e escrevam nele a data e uma palavra do dia."],
  "V2-065": ["Trem até uma cidade com museu e café com vista", "Um dia com trajeto, arte e café rende conversa em todos os momentos.", ["Escolham uma cidade com museu ou galeria perto da estação.", "Confirmem horários de trem e abertura do museu.", "Chegando, vão direto ao museu e cada um escolhe uma obra para mostrar ao outro.", "Almocem perto, sem pressa, e deixem a tarde livre.", "Tomem um café em um lugar com vista antes da volta."], "Peçam o carimbo do museu no bilhete, se houver."],
  "V2-068": ["Trem e uma música dedicada, com café à chegada", "A música dedicada no trem vira o fio do dia. O café, o ponto final dessa história.", ["Escolham uma cidade próxima com café agradável perto da estação.", "Escolha em segredo uma música sobre vocês e prepare dois fones.", "Toque no meio do trajeto, em silêncio, e diga por que escolheu.", "Ao chegar, vão direto ao café e peçam algo para dividir.", "Passeiem a pé e voltem ao fim da tarde."], "Deixe a música como toque de despedida do dia, no caminho de volta."],
  "V2-071": ["Trem e um dia para recomeçar a conversa", "Sair da rotina de trem e sem tarefa é um jeito simples de voltar a se enxergar.", ["Escolham uma cidade próxima, acessível de trem, com volta no mesmo dia.", "Confirmem horários e comprem os bilhetes com antecedência.", "No trem, sem celular, cada um fala de algo que quer fazer mais vezes juntos.", "No destino, passeiem em silêncio por 15 minutos e depois comentem o que viram.", "No almoço, brindem a algo que passaram juntos neste ano."], "Anotem as três ideias do dia e guardem para usar na semana."],
  "V2-039": ["Balsa ou passeio panorâmico, para ver a cidade de outro ângulo", "Ver a cidade ou a costa da água muda o olhar sobre um lugar que vocês já conhecem.", ["Escolham um passeio de balsa, barco ou transporte panorâmico perto de onde moram.", "Confirmem horários, valores e a previsão do tempo.", "Levem casaco, protetor solar e o celular carregado.", "Fiquem no convés ou à janela e identifiquem o que passa.", "Desembarquem, explorem a área e almocem sem pressa."], "Escolham juntos o ponto do trajeto que mais gostaram e fotografem."],
  "V2-042": ["Passeio de balsa com um postal escrito para o outro", "A água acalma, e um postal escrito à mão faz o passeio virar lembrança para guardar.", ["Escolham um passeio de balsa, barco ou transporte panorâmico perto de casa.", "Escreva em segredo um postal curto, com uma frase só sua sobre o dia ou sobre vocês.", "Entregue durante o trajeto, quando estiverem olhando a água.", "O outro lê em silêncio e responde com um abraço, ou com um postal no dia seguinte.", "Desembarquem e passeiem com calma."], "Escolham um postal do lugar para escrever na hora, se não prepararem antes."],
  "V2-045": ["Balsa ao entardecer, para falar do que fica", "A água em movimento e a luz baixa criam o clima certo para conversas que a rotina não deixa.", ["Escolham um passeio de balsa ou barco no fim da tarde, perto de onde moram.", "Confirmem horários de ida e volta e a previsão do tempo.", "Fiquem no convés, lado a lado, e olhem a água por alguns minutos sem falar.", "Cada um conta o que gostaria que não mudasse na vida de vocês.", "Desembarquem e caminhem até um lugar para um chá ou um café."], "Peguem um casaco a mais: o vento na água faz frio, mesmo no verão."],
  "V2-066": ["Passeio panorâmico com almoço à beira da água", "Um passeio pela água, seguido de uma mesa à beira dela, faz o dia caber inteiro numa só cena.", ["Escolham um passeio de barco ou balsa em uma cidade com restaurante à beira da água.", "Confirmem horários e reservem uma mesa, se possível.", "Façam o passeio primeiro, enquanto a fome ainda está pequena.", "Almocem na beira da água, sem pressa, e deixem a tarde livre.", "Voltem a pé, olhando a cidade como turistas."], "Peçam um prato para dividir: aproxima e rende conversa."],
  "V2-069": ["Passeio de balsa e um postal para abrir no almoço", "Um postal entregue durante a travessia faz o almoço depois dele ficar ainda mais bonito.", ["Escolham um passeio de barco ou balsa em uma cidade com um lugar simples para almoçar.", "Escreva em segredo um postal curto, com uma lembrança específica dos dois.", "Entregue no meio do passeio, de preferência com o vento no rosto.", "No almoço, falem do postal, sem pressa.", "Guardem o postal na carteira para ler em outro dia."], "Escrevam no verso a data e o nome do passeio."],
  "V2-072": ["Passeio pela água e um almoço para recomeçar", "Sair da cidade pela água, sem trânsito e sem pressa, dá a sensação de começar de novo.", ["Escolham um passeio de balsa, barco ou transporte panorâmico perto de onde moram.", "Confirmem horários de ida e volta e a previsão do tempo.", "Durante a travessia, guardem o celular e olhem a paisagem.", "No almoço, cada um diz uma coisa que quer recomeçar ou repetir a dois.", "Voltem na luz da tarde, em silêncio confortável."], "Anotem a frase do dia em um papel pequeno e guardem juntos."],
  // ───────── SAIR · 1 hora ─────────
  "CUL-08@75": ["Passear numa livraria e escolher um livro para o outro", "Livrarias têm cheiro de calma. Escolher um livro para a outra pessoa é um jeito de dizer 'eu te conheço'.", ["Escolham uma livraria ou sebo de bairro.", "Passeiem separados por 15 minutos.", "Cada um escolhe um livro que acha que o outro vai gostar e escreve um bilhete curto.", "Troquem os livros e leiam o primeiro parágrafo em voz alta.", "Sentem em um café próximo e conversem sobre o que escolheram."], "Se comprarem os livros, escrevam uma dedicatória curta na primeira página."],
  "GAS-10@75": ["Passeio de comida de rua, uma coisa em cada barraca", "Provar pequenas porções em barracas diferentes rende mais conversa do que um jantar sentado.", ["Escolham uma feira, esquina ou rua conhecida por comida de rua.", "Combinem um limite de gastos pequeno antes de sair.", "Provem uma coisa diferente em cada barraca e dividam tudo.", "Escolham juntos o prato do dia, aquele que merece repetir.", "Terminem com algo doce e uma caminhada curta."], "Cada um escolhe uma coisa que nunca provou e convence o outro a provar."],
  "CID-10@75": ["Descobrir uma lojinha curiosa sem precisar comprar", "Lojas pequenas e diferentes rendem boas conversas e são grátis para olhar.", ["Escolham um bairro com lojinhas independentes.", "Entrem em duas ou três sem pressa de comprar.", "Em cada uma, cada um escolhe o que mais combina com o outro e explica por quê.", "Saiam e comentem qual foi o objeto mais inesperado.", "Parem num café ou num banco de praça para fechar a conversa."], "Fotografem uma vitrine bonita e escolham qual comprariam se pudessem."],
  // ───────── SAIR · 1 hora · surpresa ─────────
  "CUL-03@75": ["Galeria de arte: cada um escolhe uma obra", "Olhar arte ao lado de alguém é ver o mundo pelos olhos dele(a) por um instante. Muitas galerias são gratuitas.", ["Escolham uma galeria ou espaço cultural com entrada gratuita ou barata.", "Passeiem separados e escolham uma obra que mais chamou a atenção.", "Levem o outro até a obra e expliquem por que gostaram dela.", "Troquem de lugar e façam o mesmo com a obra do outro.", "Saiam e escrevam juntos um título engraçado para aquela obra."], "Se a obra puder ser fotografada, façam uma foto com os dois ao lado."],
  "CUL-04@75": ["Cinema com uma surpresa escondida no bolso", "Ir ao cinema é um clássico que fica melhor com um detalhe pensado: um bilhete, um doce favorito, um lugar bom.", ["Escolham um filme em cartaz que ambos queiram ver, ou uma sessão especial mais barata.", "Compre os ingressos com antecedência para sentarem juntos.", "Leve escondido um doce favorito da outra pessoa ou um bilhete curto.", "Entreguem o bilhete antes de apagar a luz.", "Ao sair, caminhem e comentem a cena de que mais gostaram."], "Guardem o ingresso e colem num caderno com a data."],
  "GAS-05@75": ["Jantar com uma surpresa à mesa", "Um jantar vira especial quando alguém cuidou dos detalhes. Dá para escolher um lugar simples e caprichar no gesto.", ["Escolha um restaurante ou lanchonete de bairro com boa fama e cardápio acessível.", "Reserve uma mesa e deixe para a pessoa a surpresa do lugar.", "Leve um bilhete curto para entregar durante a refeição.", "Peçam algo para dividir e conversem sobre o dia sem celular na mesa.", "Dividam a sobremesa com duas colheres."], "Confirme o cardápio antes para escolher algo que a pessoa goste."],
  // ───────── SAIR · 1 hora · reconectar ─────────
  "CUL-01@75": ["Museu com um olhar de cada vez", "Museus têm silêncio e história, o clima perfeito para falar do que importa, caminhando lado a lado.", ["Escolham um museu pequeno ou uma sala de um museu maior (muitos têm entrada gratuita em dias específicos).", "Cada um escolhe uma peça e conta o que ela lembra.", "Parem diante da peça preferida do outro e escutem a história dele(a).", "Sentem no banco do museu e contem um desejo que a peça despertou.", "Saiam e conversem sobre o que mais mexeu com vocês."], "Confirmem horário e dias de entrada gratuita antes de ir."],
  "CUL-07@75": ["Uma hora de música ao vivo ou teatro de bairro", "Ver arte ao vivo junto aproxima. Muitos lugares têm apresentações curtas e baratas.", ["Procurem uma apresentação de música, teatro ou dança de bairro, ou um ensaio aberto.", "Confirmem horário e valor.", "Cheguem com 15 minutos de antecedência para sentar juntos.", "Durante a apresentação, deixem o celular guardado.", "Depois, caminhem e contem qual momento mais tocou cada um."], "Escolham um verso, uma cena ou um acorde para guardar."],
  "GAS-09@75": ["Degustação a dois com calma", "Provar bem devagar é um jeito de prestar atenção: no gosto, no cheiro e no outro.", ["Escolham algo para degustar: queijos, chocolates, cafés, frutas diferentes, doces regionais.", "Comprem pequenas porções ou provem em uma loja que ofereça degustação.", "Cada um descreve o que sente em cada prova, sem pressa.", "Votem na favorita e na mais estranha.", "Terminem escolhendo uma para repetir em casa."], "Anotem a favorita para a próxima compra."],
  // ───────── SAIR · tarde ─────────
  "CUL-01@240": ["Tarde de museu e café no fim", "Uma tarde de museu rende caminhada, silêncio e conversa, e termina bem com um café.", ["Escolham um museu e confirmem horário e dias de entrada gratuita.", "Percorram duas salas com calma e escolham uma obra favorita cada um.", "Parem em um café do museu ou de perto e conversem sobre o que viram.", "Voltem para uma terceira sala que não tinham visto.", "Terminem escrevendo juntos uma frase sobre a tarde."], "Levem um caderninho para anotar títulos das obras preferidas."],
  "CUL-03@240": ["Tarde de galerias e conversa de rua", "Percorrer galerias e espaços de arte é um programa que cabe numa tarde e rende ideias de decoração e de vida.", ["Escolham um bairro com duas ou três galerias ou espaços culturais gratuitos.", "Em cada uma, escolham uma obra e expliquem um ao outro por que gostaram.", "Entre as galerias, caminhem e parem em um café ou praça.", "Escolham uma obra que gostariam de ter em casa.", "Fechem a tarde com algo simples para comer."], "Perguntem ao guia ou ao atendente sobre a obra que mais gostaram."],
  "GAS-11@240": ["Tarde de feira e mercado, com almoço a dois", "Mercados e feiras misturam cheiro, cor e conversa. É um passeio sensorial que ainda rende o jantar.", ["Escolham uma feira ou um mercado local e confirmem o horário.", "Passeiem sem pressa e provem pequenas porções.", "Escolham juntos 3 ingredientes para levar para casa.", "Voltem e cozinhem algo simples com o que compraram.", "Comam à mesa, com música e sem tela."], "Comprem algo que nunca provaram e prometam cozinhar juntos."],
  "CUL-07@240": ["Tarde de arte ao vivo e caminhada", "Música, teatro ou dança ao vivo ficam mais bonitos se a tarde tiver um antes e um depois.", ["Procurem uma apresentação gratuita ou barata, em praça, teatro de bairro ou centro cultural.", "Cheguem cedo e passeiem pelos arredores.", "Assistam sem celular, atentos ao que acontece no palco.", "Depois, caminhem e comentem a cena de que mais gostaram.", "Fechem com um lanche simples e uma conversa tranquila."], "Escolham uma frase da apresentação para repetir durante a semana."],
  "MOV-06@240": ["Tarde de boliche com brincadeira no placar", "Boliche é um jogo leve que deixa os dois competindo e rindo. Perfeito para quem quer se mexer e se divertir.", ["Escolham uma pista de boliche e confirmem horários e valores.", "Combinem uma aposta carinhosa: quem perder paga o lanche ou escolhe o próximo programa.", "Joguem duas partidas, sem levar o placar muito a sério.", "Façam uma pausa para beliscar e conversar.", "Comemorem a vitória e o consolo do perdedor com um abraço."], "Escolham um apelido engraçado para cada um aparecer no placar."],
  "GAS-13@240": ["Jantar temático, com figurino e tudo", "Um tema transforma o jantar em aventura: pode ser italiano, japonês, anos 80 ou mexicano.", ["Escolham um tema e uma cozinha que possam fazer ou pedir.", "Combinem pequenos detalhes: roupa, música, enfeites na mesa.", "Cozinhem ou escolham um lugar que combine com o tema.", "Comam devagar, brindando a cada prato.", "Terminem com um filme ou uma música do tema."], "Deem um nome ao jantar e criem um cardápio escrito à mão."],
  // ───────── SAIR · tarde · reconectar ─────────
  "CUL-08@240": ["Tarde na livraria, com leitura em voz alta", "Passar a tarde entre livros e ler em voz alta um trecho um para o outro é um programa raro e cheio de intimidade.", ["Escolham uma livraria, sebo ou biblioteca com espaço para sentar.", "Cada um escolhe um livro e lê em voz alta um trecho curto para o outro.", "Troquem de livros e continuem a leitura.", "Conversem sobre o que as palavras fizeram sentir.", "Fechem a tarde com um café e uma lista de livros que querem ler."], "Anotem juntos uma frase que queiram guardar da tarde."],
  "CUL-04@240": ["Sessão dupla: filme e conversa no café", "Um filme escolhido a dois, seguido de uma conversa sobre ele, vira um programa completo.", ["Escolham um filme que ambos queiram ver, em cinema ou em sessão gratuita de espaço cultural.", "Comprem os ingressos com antecedência e cheguem cedo.", "Depois do filme, sentem em um café e comentem a cena favorita de cada um.", "Conversem sobre um personagem com quem se identificaram.", "Escolham o próximo filme que verão juntos."], "Guardem os ingressos para colar num caderno ou álbum."],
  "GAS-05@240": ["Jantar sem pressa e sem celular", "Uma refeição longa, sem tela, é rara hoje. Um jantar bem escolhido e conversa a dois bastam.", ["Escolham um restaurante ou lanchonete aconchegante e reservem se necessário.", "Guardem os celulares no bolso, em modo silencioso.", "Peçam um prato principal e uma entrada para dividir.", "Façam perguntas curtas e profundas: um medo, um sonho, um arrependimento bom.", "Fechem com uma sobremesa e um agradecimento mútuo."], "Combinem que o primeiro a pegar o celular paga a sobremesa."],
  // ───────── ESPECIAIS (sair, grátis) ─────────
  "V2-073": ["Garimpar uma loja de segunda mão, sem comprar nada", "Brechós e lojas de usados são museus de objetos com história, e ver tudo é grátis.", ["Escolham um brechó, uma loja de segunda mão ou um bazar de bairro.", "Combinem de antemão que não vão comprar nada.", "Cada um procura um objeto, uma peça ou um livro que combine com o outro e explica por quê.", "Imaginem juntos a história de um objeto antigo.", "Saiam e escolham o achado mais curioso do dia."], "Fotografem o objeto mais estranho e deem um nome a ele."],
  "V2-074": ["Cartas curtas escolhidas na biblioteca", "A biblioteca é silêncio, papel e tempo. Escrever cartas curtas lá dentro dá a elas um peso especial.", ["Vão a uma biblioteca pública ou espaço de leitura gratuito.", "Cada um escolhe um livro e anota uma frase que lembre o outro.", "Escrevam uma carta curta com a frase e uma frase própria.", "Troquem as cartas e leiam em silêncio.", "Do lado de fora, conversem sobre o que sentiram ao ler."], "Deixem a carta dentro do livro para o próximo leitor, ou guardem a sua."],
  "V2-075": ["Um desenho-surpresa na biblioteca", "Desenhar em silêncio, lado a lado, e entregar o desenho como presente é simples e inesquecível.", ["Vão a uma biblioteca pública ou espaço de leitura gratuito.", "Levem papel e lápis de casa.", "Cada um desenha em segredo um retrato rápido do outro ou algo que lembre os dois.", "Troquem os desenhos e escrevam no verso uma frase carinhosa.", "Guardem o desenho do outro e levem para casa."], "Assinem o desenho e anotem a data."],
  "V2-076": ["Escolher uma fotografia para revisitar", "Uma foto antiga é uma porta aberta para um dia que vocês viveram. Voltar a ele a dois reaproxima.", ["Escolham uma foto, impressa ou no celular, de um dia especial.", "Vão a um lugar calmo: um parque, uma praça, uma biblioteca.", "Contem, um de cada vez, tudo o que lembram daquele dia.", "Façam uma foto nova, no mesmo lugar ou com a mesma pose.", "Comparem as duas e comentem o que mudou e o que continua igual."], "Guardem as duas fotos lado a lado."],
  "V2-077": ["Uma tarde de voluntariado leve", "Ajudar juntos, mesmo por poucas horas, cria uma lembrança que vale mais que um jantar.", ["Procurem uma ação de voluntariado que aceite ajuda pontual: abrigo, banco de alimentos, horta comunitária, campanha de arrecadação.", "Confirmem horário e tarefa antes de ir.", "Vão com roupa confortável e disposição.", "Trabalhem lado a lado, sem pressa e com respeito.", "Terminem conversando sobre o que sentiram e o que gostariam de repetir."], "Combinem uma data para voltar."],
  "V2-078": ["Desenho livre num espaço público calmo", "Sentar numa praça ou jardim e desenhar o que se vê é uma tarde grátis e cheia de olhares.", ["Levem papel, lápis e algo para se apoiar.", "Escolham um jardim, uma praça ou um banco com boa vista.", "Cada um desenha o que está vendo, sem se preocupar com o resultado.", "Troquem os desenhos e comentem o que o outro enxergou.", "Façam um desenho juntos no mesmo papel."], "Assinem os desenhos e escrevam a data."],
  "V2-079": ["Colagem com envelope-surpresa", "Um envelope fechado, cheio de recortes e bilhetes, vira presente e passatempo ao mesmo tempo.", ["Prepare, sem a pessoa ver, um envelope com recortes de revistas, frases suas, uma foto e uma pequena instrução.", "Escolham um lugar tranquilo e público, como um parque ou a biblioteca, com uma mesa disponível.", "Abram o envelope juntos e montem uma colagem com o que está dentro.", "Cada um acrescenta um recorte ou uma frase.", "Levem a colagem para casa e escolham onde pendurar."], "Dentro do envelope, deixe uma frase que só vocês dois entendem."],
  "V2-080": ["Decorar um canto com um envelope-surpresa", "Um envelope com ideias de decoração e bilhetes carinhosos vira uma tarde de projeto a dois.", ["Prepare em segredo um envelope com papéis coloridos, uma lista de ideias e um bilhete.", "Escolham um lugar calmo e público que permita atividades pequenas, como um jardim.", "Abram o envelope e montem juntos um pequeno enfeite, como uma guirlanda ou um móbile de papel.", "Conversem sobre o canto da casa que querem decorar.", "Levem o enfeite e pendurem em casa, no mesmo dia."], "Escolham juntos um nome para o canto decorado."],
  "V2-081": ["Montar um álbum à mão numa tarde sem tela", "Um álbum de papel, feito com tempo e sem celular, é presente e lembrança.", ["Reúnam fotos impressas, bilhetes, ingressos e desenhos que tiverem.", "Vão a um lugar tranquilo onde possam sentar e espalhar o material: uma biblioteca, um jardim, um café com mesa.", "Escolham juntos as peças e o que vai em cada página.", "Colem e escrevam uma legenda curta em cada uma.", "Deixem a última página em branco."], "Escrevam na primeira página uma dedicatória a quatro mãos."],
  "V2-082": ["Cuidar de um jardim comunitário", "Cuidar de plantas juntos é paciência e carinho transformados em tarefa. E o resultado cresce.", ["Procurem um jardim ou horta comunitária que aceite ajuda pontual.", "Confirmem dias, horários e o que é preciso levar.", "Vão com roupa confortável e luvas, se tiverem.", "Plantem, reguem ou capinem um canteiro juntos.", "Voltem, se puderem, depois de algumas semanas para ver como cresceu."], "Escolham uma planta para acompanhar e deem um nome a ela."],
};

// Surpresas: o tipo vem dos dados; aqui só o texto mostrado.
export const SURPRISE = {
  "Cartas curtas escolhidas na biblioteca": "A surpresa é a carta: escreva a sua em segredo, antes, para entregar quando a pessoa menos esperar.",
  "Um desenho surpresa na biblioteca": "A surpresa é o desenho: faça o retrato em segredo e entregue só no final, com uma frase no verso.",
  "Colagem com envelope surpresa": "A surpresa é o envelope: prepare-o em segredo e só revele o conteúdo quando estiverem sentados, prontos para montar.",
  "Decoração com envelope surpresa": "A surpresa é o envelope: prepare-o em segredo, com as ideias e o bilhete, e entregue quando chegarem ao lugar.",
  "Bilhete curto e específico": "Deixe um bilhete curto, escrito à mão, com uma lembrança específica dos dois (não um 'te amo' genérico) para ser lido na hora certa.",
  "Música dedicada": "Escolha em segredo uma música que fale de vocês dois e toque no momento certo, dizendo por que a escolheu.",
  "Postal escrito": "Escreva um postal curto, com uma frase só sua, e entregue sem aviso no meio do programa.",
};

export const PLAN_B = {
  home: "Se alguma coisa der errado, façam a versão curta: música, algo gostoso para beliscar e uma conversa sem celular.",
  outdoors: "Se o tempo virar, levem a mesma ideia para dentro de casa: música, algo gostoso e uma conversa com a luz baixa.",
  "go-out": "Se o lugar estiver fechado ou lotado, escolham um café tranquilo ou uma caminhada pelo bairro e mantenham a ideia da conversa.",
};

import * as en from "./ideias-textos-en.mjs";
import * as es from "./ideias-textos-es.mjs";
import { NIGHT_T } from "./ideias-noite.mjs";
import { FLAME_T } from "./ideias-chama.mjs";
import { FLAME_MORE_T } from "./ideias-chama-mais.mjs";
import { EXTRA_T } from "./ideias-extra.mjs";

const PACKS = { pt: { T, SURPRISE, PLAN_B }, en, es };

export function editorialText(variant, lang = "pt") {
  const pack = PACKS[lang] ?? PACKS.pt;
  const night = NIGHT_T[lang] ?? NIGHT_T.pt;
  const flame = { ...(FLAME_T[lang] ?? FLAME_T.pt), ...(FLAME_MORE_T[lang] ?? FLAME_MORE_T.pt) };
  const extra = EXTRA_T[lang] ?? EXTRA_T.pt;
  const entry = extra[variant.id] ?? flame[variant.id] ?? night[variant.id] ?? pack.T[variant.id] ?? pack.T[`${variant.familyId}@${variant.durationMinutes}`];
  if (!entry) return null;
  const [title, whyItFits, howTo, smallDetail, planB, surpriseText] = entry;
  const key = String(variant.surprise ?? "").replace(/^Surpresa identificável:\s*/, "").replace(/\.$/, "");
  const surprise = surpriseText ?? (variant.surprise ? (pack.SURPRISE[key] ?? undefined) : undefined);
  return { title, whyItFits, howTo, smallDetail, planB: planB ?? pack.PLAN_B[variant.environment], surprise };
}
