"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

type Lookup = { status: "new" | "read" | "responded" | "archived"; response: string | null; respondedAt: string | null; alias: string | null; expiresAt: string | null };

export function ResponseLookupEs({ initialCode = "" }: { initialCode?: string }) {
  const [code, setCode] = useState(initialCode); const [result, setResult] = useState<Lookup | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [deleting, setDeleting] = useState(false); const [deleted, setDeleted] = useState(false);
  async function lookup(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setResult(null); setDeleted(false); try { const response = await fetch(`/api/listening?code=${encodeURIComponent(code)}&lang=es`); const payload = await response.json() as Lookup; if (!response.ok) throw new Error("No hemos encontrado un relato con ese código."); setResult(payload); } catch (caught) { setError(caught instanceof Error ? caught.message : "No hemos podido consultarlo ahora."); } finally { setBusy(false); } }
  async function deleteReport() { if (!window.confirm("¿Quieres borrar definitivamente tu relato y cualquier respuesta? Esta acción no se puede deshacer.")) return; setDeleting(true); setError(""); try { const response = await fetch(`/api/listening?code=${encodeURIComponent(code)}&lang=es`, { method: "DELETE" }); if (!response.ok) throw new Error("No hemos podido borrarlo ahora."); setResult(null); setCode(""); setDeleted(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "No hemos podido borrarlo ahora."); } finally { setDeleting(false); } }
  return <div className="response-card"><form onSubmit={lookup}><label><span>Tu código privado</span><input value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} minLength={10} maxLength={40} placeholder="SR-XXXX-XXXX-XXXX-XXXX-XXXX" autoComplete="off" required /></label><button className="button primary" disabled={busy}>{busy ? "Consultando…" : "Consultar"}<span>→</span></button></form>{error && <p className="response-error" role="alert">{error}</p>}{deleted && <p className="response-deleted" role="status">Tu relato y la respuesta vinculada se han borrado definitivamente.</p>}{result && <article className={`response-result ${result.status}`}><p className="eyebrow">{result.status === "responded" ? "HEMOS DEJADO UNA PALABRA PARA TI" : result.status === "read" ? "HEMOS LEÍDO TU RELATO" : result.status === "archived" ? "ESCUCHA FINALIZADA" : "TENEMOS TU RELATO"}</p><h2>{result.status === "responded" ? `${result.alias ? `${result.alias}, ` : ""}gracias por volver.` : result.status === "read" ? "Lo hemos leído con atención." : "Está esperando nuestra lectura."}</h2>{result.response ? <div className="response-letter">{result.response.split("\n").map((paragraph) => paragraph.trim() && <p key={paragraph}>{paragraph}</p>)}</div> : <p>{result.status === "read" ? "Si pediste una palabra, estamos preparando la respuesta con cuidado. Vuelve a consultarlo con el mismo código." : "No hay una respuesta disponible en este momento. Puedes volver más adelante."}</p>}{result.expiresAt && <p className="response-expiry">Eliminación automática prevista antes del {new Intl.DateTimeFormat("es-ES", { dateStyle: "long" }).format(new Date(result.expiresAt))}.</p>}<button className="response-delete" type="button" disabled={deleting} onClick={deleteReport}>{deleting ? "Borrando…" : "Borrar mi relato ahora"}</button></article>}<p className="response-help">¿Has perdido el código? Por seguridad, no podemos recuperarlo. Puedes <Link href="/es/entre-nos">enviar un nuevo relato</Link>.</p></div>;
}
