"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export function CommunityFormEs() {
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/community", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: data.get("kind"), authorName: data.get("authorName"), email: data.get("email"), title: data.get("title"), content: data.get("content"), location: data.get("location"), anonymous: data.get("anonymous") === "on", consent: data.get("consent") === "on", website: data.get("website"), language: "es-ES" }) }); if (!response.ok) throw new Error(); form.reset(); setStatus("success"); } catch { setStatus("error"); } }
  return <form className="community-form" onSubmit={submit}><label><span>¿Qué quieres compartir?</span><select name="kind" defaultValue="story" required><option value="story">Una historia</option><option value="idea">Una idea para parejas</option><option value="surprise">Una sorpresa que salió bien</option></select></label><div className="form-row"><label><span>Nombre o alias (opcional)</span><input name="authorName" maxLength={80} /></label><label><span>Correo electrónico</span><input name="email" type="email" maxLength={160} required /></label></div><label><span>Título</span><input name="title" minLength={4} maxLength={120} required /></label><label><span>Tu historia o idea</span><textarea name="content" minLength={40} maxLength={3000} rows={9} required /><small>Evita datos que identifiquen a otras personas.</small></label><label><span>Lugar o ciudad (opcional)</span><input name="location" maxLength={120} /></label><label className="community-check"><input name="anonymous" type="checkbox" /><span>Si se publica, quiero que aparezca de forma anónima.</span></label><label className="community-check"><input name="consent" type="checkbox" required /><span>Autorizo la revisión editorial de esta aportación y he leído las <Link href="/es/terminos">Condiciones</Link>, la <Link href="/es/privacidad">Política de privacidad</Link> y las <Link href="/es/normas-de-la-comunidad">Normas de la comunidad</Link>.</span></label><label className="community-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><button className="button primary" disabled={status === "sending"}>{status === "sending" ? "Enviando…" : "Enviar para revisión"} <span>→</span></button><p className={`community-message ${status}`} role="status" aria-live="polite">{status === "success" ? "Aportación recibida. La revisaremos antes de cualquier publicación." : status === "error" ? "No hemos podido enviarla ahora. Revisa los campos e inténtalo de nuevo." : ""}</p></form>;
}
