"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

type Lookup = { status: "new" | "read" | "responded" | "archived"; response: string | null; respondedAt: string | null; alias: string | null; expiresAt: string | null };

export function ResponseLookupEn({ initialCode = "" }: { initialCode?: string }) {
  const [code, setCode] = useState(initialCode); const [result, setResult] = useState<Lookup | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [deleting, setDeleting] = useState(false); const [deleted, setDeleted] = useState(false);
  async function lookup(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setResult(null); setDeleted(false); try { const response = await fetch(`/api/listening?code=${encodeURIComponent(code)}&lang=en`); const payload = await response.json() as Lookup; if (!response.ok) throw new Error("We couldn't find a story with that code."); setResult(payload); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn't check it right now."); } finally { setBusy(false); } }
  async function deleteReport() { if (!window.confirm("Do you want to permanently delete your story and any reply? This cannot be undone.")) return; setDeleting(true); setError(""); try { const response = await fetch(`/api/listening?code=${encodeURIComponent(code)}&lang=en`, { method: "DELETE" }); if (!response.ok) throw new Error("We couldn't delete it right now."); setResult(null); setCode(""); setDeleted(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn't delete it right now."); } finally { setDeleting(false); } }
  return <div className="response-card"><form onSubmit={lookup}><label><span>Your private code</span><input value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} minLength={10} maxLength={40} placeholder="SR-XXXX-XXXX-XXXX-XXXX-XXXX" autoComplete="off" required /></label><button className="button primary" disabled={busy}>{busy ? "Checking…" : "Check"}<span>→</span></button></form>{error && <p className="response-error" role="alert">{error}</p>}{deleted && <p className="response-deleted" role="status">Your story and its linked reply have been permanently deleted.</p>}{result && <article className={`response-result ${result.status}`}><p className="eyebrow">{result.status === "responded" ? "WE HAVE LEFT A WORD FOR YOU" : result.status === "read" ? "WE HAVE READ YOUR STORY" : result.status === "archived" ? "LISTENING CLOSED" : "WE HAVE YOUR STORY"}</p><h2>{result.status === "responded" ? `${result.alias ? `${result.alias}, ` : ""}thank you for coming back.` : result.status === "read" ? "We have read it with care." : "It is waiting for us to read it."}</h2>{result.response ? <div className="response-letter">{result.response.split("\n").map((paragraph) => paragraph.trim() && <p key={paragraph}>{paragraph}</p>)}</div> : <p>{result.status === "read" ? "If you asked for a word, we are preparing the reply with care. Check again later with the same code." : "There is no reply available at the moment. You can come back later."}</p>}{result.expiresAt && <p className="response-expiry">Automatic deletion is scheduled before {new Intl.DateTimeFormat("en-US", { dateStyle: "long" }).format(new Date(result.expiresAt))}.</p>}<button className="response-delete" type="button" disabled={deleting} onClick={deleteReport}>{deleting ? "Deleting…" : "Delete my story now"}</button></article>}<p className="response-help">Lost your code? For security reasons, we can&apos;t recover it. You can <Link href="/en/between-us">send a new story</Link>.</p></div>;
}
