import type { Metadata } from "next";
import { LegalPage } from "../legal/LegalPage";

export const metadata: Metadata = { title: "Política de Privacidade", description: "Como o Simple & Romantic trata dados pessoais, contribuições e inscrições.", alternates: { canonical: "/privacidade" } };

export default function PrivacyPage() {
  return <LegalPage kicker="TRANSPARÊNCIA E CUIDADO" title="Política de Privacidade" intro="Esta política explica, em linguagem simples, quais dados usamos e por quê. Última atualização: 1º de agosto de 2026.">
    <h2>1. Responsável pelo tratamento</h2><p><strong>Responsável pelo tratamento:</strong> Simple & Romantic, projeto editorial independente administrado por Bruno de Oliveira Cardoso.</p><p><strong>Contato:</strong> solicitações relacionadas à privacidade podem ser enviadas pelo <a href="/contato">formulário de contato do site</a>.</p>
    <h2>2. Dados que você escolhe enviar</h2><p>Podemos receber nome ou apelido, e-mail, cidade, histórias, ideias, mensagens de contato e inscrição no guia. O e-mail de quem envia uma contribuição é usado para contato e moderação e não aparece publicamente.</p>
    <h2>3. Como e por que usamos esses dados</h2><ul><li>com seu consentimento, receber e responder relatos do Entre nós, enviar o guia e avaliar contribuições para publicação;</li><li>executar o serviço que você solicitou, como responder uma mensagem de contato;</li><li>proteger o site e seus leitores contra spam, fraude e abuso, com base no interesse legítimo de manter o serviço seguro;</li><li>cumprir obrigações legais quando aplicáveis.</li></ul><p>Você pode retirar um consentimento a qualquer momento. A retirada não invalida o tratamento realizado anteriormente de forma legítima.</p>
    <h2>4. Publicação de histórias</h2><p>Nenhuma contribuição é publicada automaticamente. A equipe revisa o material e pode ajustar ortografia ou clareza sem alterar o sentido. Se você escolher publicação anônima, seu nome não será exibido.</p>
    <h2>5. Espaço Entre nós</h2><p>O espaço de escuta permite enviar um relato sem informar nome ou e-mail. Guardamos o apelido opcional, a finalidade escolhida, o relato, a autorização opcional para publicação, a resposta preparada e um código aleatório de acompanhamento. O relato permanece privado por padrão. A autorização para uma possível publicação é separada e não garante que o texto será publicado.</p><p>Não envie nomes completos, endereços, telefones, documentos, dados de saúde identificáveis ou informações que permitam reconhecer terceiros. O código de acompanhamento deve ser guardado em segurança, pois permite consultar o estado e a resposta vinculada ao relato.</p>
    <h2>6. Compartilhamento</h2><p>Não vendemos dados pessoais. Podemos usar prestadores técnicos necessários para hospedar o site e armazenar os dados, sempre limitados à operação do serviço ou ao cumprimento da lei.</p>
    <h2>7. Estatísticas de uso</h2><p>Contamos visualizações de páginas de forma agregada e sem cookies. O relatório interno guarda apenas o dia, a página acessada, a origem geral da visita e a quantidade de visualizações. Não armazenamos nome, e-mail, endereço IP nem histórico individual nessa medição.</p>
    <h2>8. Prazos de conservação e eliminação</h2><ul><li><strong>Entre nós — novo ou lido:</strong> até 180 dias depois do envio;</li><li><strong>Entre nós — respondido:</strong> até 90 dias depois da resposta;</li><li><strong>Entre nós — arquivado:</strong> até 30 dias depois do encerramento;</li><li><strong>Mensagens de contato:</strong> até 12 meses depois da última interação, salvo obrigação legal;</li><li><strong>Contribuições não publicadas:</strong> até 12 meses depois da decisão editorial;</li><li><strong>Contribuições publicadas:</strong> enquanto permanecerem no blog ou até a retirada da autorização;</li><li><strong>Inscrição no guia:</strong> até o cancelamento ou retirada do consentimento.</li></ul><p>Cada relato do Entre nós recebe uma data de expiração. Registros vencidos são eliminados durante as rotinas do serviço. A própria pessoa pode eliminá-lo antes, usando o código particular na página de consulta. Aplicamos controles razoáveis de acesso, mas nenhum serviço on-line elimina todos os riscos.</p>
    <h2>9. Seus direitos</h2><p>Você pode solicitar informação, acesso, correção, exclusão, limitação, portabilidade ou oposição ao tratamento, bem como retirar consentimentos. Envie a solicitação pela página de <a href="/contato">Contato</a>. No Entre nós, o código particular permite eliminar diretamente o relato e ajuda a confirmar outras solicitações. Você também pode apresentar reclamação à autoridade de proteção de dados do país onde reside, trabalha ou onde considera ter ocorrido uma infração.</p>
    <h2>10. Crianças e dados de terceiros</h2><p>Não envie dados pessoais, imagens ou histórias identificáveis de terceiros sem autorização. O serviço e o espaço Entre nós são destinados exclusivamente a pessoas com 18 anos ou mais.</p>
    <h2>11. Alterações</h2><p>Esta política pode ser atualizada para acompanhar novas funções ou exigências legais. A data no início identifica a versão vigente.</p>
  </LegalPage>;
}
